import { useEffect, useState } from 'react';
import { Link, useLocation } from 'wouter';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Activity, ArrowLeft, Ban, BarChart3, Building2, Check, CircleDollarSign, FileCheck2, Gauge, ListChecks, Loader2, LockKeyhole, Pencil, Settings2, ShieldAlert, ShieldCheck, Trash2, TrendingUp, Users, WalletCards, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { toast } from 'sonner';
import { trpc } from '@/lib/trpc';
import { useAuth } from '@/_core/hooks/useAuth';

const money = (value: number) => `${value.toLocaleString('fr-MA')} MAD`;
const statusLabel: Record<string, string> = { active: 'نشط', suspended: 'موقوف', banned: 'محظور' };

export default function AdminDashboard() {
  const { user, loading } = useAuth();
  const [, navigate] = useLocation();
  const enabled = user?.role === 'admin';
  const overview = trpc.admin.overview.useQuery(undefined, { enabled });
  const users = trpc.admin.users.useQuery(undefined, { enabled });
  const listings = trpc.admin.listings.useQuery(undefined, { enabled });
  const settings = trpc.admin.commissionSettings.useQuery(undefined, { enabled });
  const auditLogs = trpc.admin.auditLogs.useQuery(undefined, { enabled });
  const payments = trpc.admin.payments.useQuery(undefined, { enabled });
  const payouts = trpc.admin.payouts.useQuery(undefined, { enabled });
  const kyc = trpc.kyc.adminList.useQuery(undefined, { enabled });
  const [tab, setTab] = useState('overview');
  const [rate, setRate] = useState('10');
  const [platformForm, setPlatformForm] = useState({ platformName: 'B2-Rent', contactEmail: '', contactPhone: '', maintenanceMode: false });
  const [editing, setEditing] = useState<number | null>(null);
  const [editTitle, setEditTitle] = useState('');
  const [editPrice, setEditPrice] = useState('');

  useEffect(() => { if (!loading && user && user.role !== 'admin') navigate('/'); }, [loading, user, navigate]);
  useEffect(() => { if (settings.data) { setRate(String(settings.data.commissionRateBasisPoints / 100)); setPlatformForm({ platformName: settings.data.platformName, contactEmail: settings.data.contactEmail || '', contactPhone: settings.data.contactPhone || '', maintenanceMode: settings.data.maintenanceMode }); } }, [settings.data]);

  const refresh = async () => { await Promise.all([overview.refetch(), users.refetch(), listings.refetch(), auditLogs.refetch(), settings.refetch()]); };
  const notify = (message: string) => ({ onSuccess: async () => { toast.success(message); await refresh(); }, onError: (error: { message: string }) => { toast.error(error.message); } });
  const updateStatus = trpc.admin.updateUserStatus.useMutation(notify('تم تحديث حالة الحساب'));
  const moderateListing = trpc.admin.moderateListing.useMutation(notify('تم تحديث الإعلان'));
  const updateListing = trpc.admin.updateListing.useMutation({ ...notify('تم حفظ تعديلات الإعلان'), onSuccess: async () => { setEditing(null); await refresh(); } });
  const deleteListing = trpc.admin.deleteListing.useMutation(notify('تم حذف الإعلان'));
  const updateCommission = trpc.admin.updateCommission.useMutation(notify('تم تحديث العمولة'));
  const updateSettings = trpc.admin.updatePlatformSettings.useMutation(notify('تم حفظ إعدادات المنصة'));
  const reviewKyc = trpc.kyc.review.useMutation(notify('تم تحديث طلب التحقق'));

  if (loading || !user) return <div className="grid min-h-screen place-items-center"><Loader2 className="animate-spin text-cyan-500" /></div>;
  if (!enabled) return null;
  const stats = overview.data;
  const pendingKyc = kyc.data?.filter(item => item.status === 'Pending').length || 0;
  const kpis: Array<[string, string | number, typeof CircleDollarSign, string]> = [['إيرادات المنصة', money(stats?.grossRevenue || 0), CircleDollarSign, 'text-emerald-600'], ['عمولة مكتسبة', money(stats?.platformFees || 0), WalletCards, 'text-amber-600'], ['وكالات نشطة', stats?.activeAgencies || 0, Building2, 'text-sky-600'], ['إجمالي الحجوزات', stats?.bookings || 0, ListChecks, 'text-violet-600'], ['نمو المستخدمين', `+${stats?.userGrowth || 0}`, TrendingUp, 'text-rose-600']];

  return <main dir="rtl" className="min-h-screen bg-[#f4f7f6] px-4 py-5 text-slate-900 sm:px-6 lg:px-10">
    <div className="mx-auto max-w-[1440px] space-y-5">
      <header className="flex flex-col gap-5 rounded-2xl bg-[#102d2b] p-6 text-white shadow-xl sm:flex-row sm:items-end sm:justify-between"><div><div className="mb-3 flex items-center gap-2 text-emerald-300"><Gauge className="h-4 w-4" /><span className="text-xs font-bold uppercase tracking-[0.2em]">B2-Rent / CONTROL ROOM</span></div><h1 className="text-3xl font-black tracking-tight">مركز التحكم بالمنصة</h1><p className="mt-2 max-w-xl text-sm text-emerald-50/70">إدارة الوكالات، المحتوى، الأموال، والثقة من مساحة واحدة.</p></div><Link href="/host"><Button variant="outline" className="w-fit border-white/20 bg-transparent text-white hover:bg-white/10"><ArrowLeft className="ml-2 h-4 w-4" /> لوحة الشريك</Button></Link></header>
        <section className="grid grid-cols-2 gap-3 xl:grid-cols-5">{kpis.map(([label, value, Icon, color]) => <Card key={String(label)} className="border-0 shadow-sm"><CardContent className="p-4"><Icon className={`mb-4 h-5 w-5 ${color}`} /><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-xl font-black text-[#102d2b]">{value}</p><p className="mt-1 text-[10px] text-slate-400">آخر 30 يوماً حسب المتاح</p></CardContent></Card>)}</section>
      <Tabs value={tab} onValueChange={setTab} dir="rtl"><TabsList className="flex h-auto w-full flex-wrap justify-start gap-1 rounded-xl bg-white p-1 shadow-sm"><Tab value="overview" icon={BarChart3}>نظرة عامة</Tab><Tab value="users" icon={Users}>الوكالات والمستخدمون</Tab><Tab value="listings" icon={ListChecks}>المحتوى</Tab><Tab value="finance" icon={WalletCards}>المالية</Tab><Tab value="settings" icon={Settings2}>إعدادات المنصة</Tab><Tab value="audit" icon={LockKeyhole}>الأمان والتدقيق</Tab></TabsList>
        <TabsContent value="overview" className="mt-4 grid gap-4 lg:grid-cols-[1.5fr_1fr]"><Card><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><TrendingUp className="h-5 w-5 text-emerald-600" />اتجاه الإيرادات</CardTitle></CardHeader><CardContent><div className="h-72"><ResponsiveContainer width="100%" height="100%"><AreaChart data={stats?.monthlyRevenue || []}><defs><linearGradient id="revenueFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#10b981" stopOpacity={0.35} /><stop offset="100%" stopColor="#10b981" stopOpacity={0} /></linearGradient></defs><CartesianGrid vertical={false} stroke="#e5eeeb" /><XAxis dataKey="label" tickLine={false} axisLine={false} /><YAxis tickLine={false} axisLine={false} tickFormatter={value => `${value / 1000}k`} /><Tooltip formatter={(value: number) => [money(value), 'الإيرادات']} /><Area type="monotone" dataKey="revenue" stroke="#059669" fill="url(#revenueFill)" strokeWidth={3} /></AreaChart></ResponsiveContainer></div></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><Activity className="h-5 w-5 text-amber-600" />آخر نشاط إداري</CardTitle></CardHeader><CardContent className="space-y-3">{auditLogs.data?.slice(0, 6).map(item => <ActivityRow key={item.id} action={item.action} detail={`${item.entityType}${item.entityId ? ` #${item.entityId}` : ''}`} date={item.createdAt} />) || <Empty text="لا توجد أحداث بعد." />}</CardContent></Card></TabsContent>
        <TabsContent value="users" className="mt-4 space-y-4"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Users className="h-5 w-5 text-emerald-600" />دليل الوكالات والمستخدمين <Badge variant="secondary">{users.data?.length || 0}</Badge></CardTitle></CardHeader><CardContent className="space-y-2">{users.data?.map(item => <div key={item.id} className="flex flex-col gap-3 border-b py-4 last:border-0 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="flex items-center gap-2"><p className="truncate font-bold">{item.agencyName || item.name || 'بدون اسم'}</p><Badge variant="outline">{item.role}</Badge></div><p className="text-xs text-slate-500">{item.email || 'بدون بريد'} {item.commercialRegister ? ` · RC ${item.commercialRegister}` : ''}</p></div><div className="flex flex-wrap items-center gap-2"><Badge variant={item.accountStatus === 'active' ? 'default' : item.accountStatus === 'banned' ? 'destructive' : 'secondary'}>{statusLabel[item.accountStatus]}</Badge>{item.kycVerificationStatus === 'verified' && <Badge className="bg-emerald-50 text-emerald-700"><ShieldCheck className="ml-1 h-3 w-3" />موثق</Badge>}{item.accountStatus !== 'banned' && <Button size="sm" variant="outline" onClick={() => updateStatus.mutate({ userId: item.id, status: item.accountStatus === 'suspended' ? 'active' : 'suspended' })}>{item.accountStatus === 'suspended' ? <><Check className="ml-1 h-3 w-3" />تفعيل</> : <><Ban className="ml-1 h-3 w-3" />إيقاف</>}</Button>}{item.accountStatus !== 'banned' && <Button size="sm" variant="destructive" onClick={() => updateStatus.mutate({ userId: item.id, status: 'banned' })}>حظر</Button>}</div></div>) || <Empty text="لا يوجد مستخدمون." />}</CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><FileCheck2 className="h-5 w-5 text-amber-600" />طابور التحقق <Badge variant="secondary">{pendingKyc}</Badge></CardTitle></CardHeader><CardContent className="space-y-2">{kyc.data?.filter(item => item.status === 'Pending').map(item => <div key={item.id} className="flex flex-col gap-3 rounded-lg border p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold">{item.originalFileName}</p><p className="text-xs text-slate-500">#{item.userId} · {item.applicantRole} · {item.documentType}</p></div><div className="flex gap-2"><Button size="sm" onClick={() => reviewKyc.mutate({ id: item.id, status: 'Approved' })}>قبول</Button><Button size="sm" variant="destructive" onClick={() => reviewKyc.mutate({ id: item.id, status: 'Rejected', rejectionReason: 'لم تجتز المراجعة الإدارية.' })}>رفض</Button></div></div>) || <Empty text="لا توجد طلبات معلقة." />}</CardContent></Card></TabsContent>
        <TabsContent value="listings" className="mt-4"><Card><CardHeader><CardTitle className="flex items-center gap-2"><ListChecks className="h-5 w-5 text-emerald-600" />مراقبة كل الإعلانات</CardTitle></CardHeader><CardContent className="space-y-3">{listings.data?.map(item => <div key={item.id} className="rounded-xl border p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0 flex-1">{editing === item.id ? <div className="flex flex-col gap-2 sm:flex-row"><input className="rounded-lg border p-2 text-sm" value={editTitle} onChange={event => setEditTitle(event.target.value)} /><input className="w-32 rounded-lg border p-2 text-sm" type="number" value={editPrice} onChange={event => setEditPrice(event.target.value)} /></div> : <><p className="font-bold text-[#102d2b]">{item.title}</p><p className="text-xs text-slate-500">{item.category} · {item.ownerName || `مالك #${item.ownerId}`} · {money(item.pricePerDay)}</p></>}</div><div className="flex flex-wrap items-center gap-2"><Badge variant={item.status === 'Rejected' ? 'destructive' : item.status === 'Published' ? 'default' : 'secondary'}>{item.status}</Badge>{item.isFeatured && <Badge className="bg-amber-50 text-amber-700">مميز</Badge>}{editing === item.id ? <><Button size="sm" onClick={() => updateListing.mutate({ listingId: item.id, title: editTitle, pricePerDay: Number(editPrice) })}><Check className="ml-1 h-3 w-3" />حفظ</Button><Button size="sm" variant="ghost" onClick={() => setEditing(null)}><X className="h-3 w-3" /></Button></> : <><Button size="icon" variant="outline" title="تعديل الإعلان" onClick={() => { setEditing(item.id); setEditTitle(item.title); setEditPrice(String(item.pricePerDay)); }}><Pencil className="h-4 w-4" /></Button><Button size="icon" variant="outline" title="تمييز الإعلان" onClick={() => moderateListing.mutate({ listingId: item.id, status: item.status === 'Rejected' ? 'Published' : item.status as 'Published' | 'Approved' | 'Rejected', isFeatured: !item.isFeatured })}><TrendingUp className="h-4 w-4" /></Button><Button size="icon" variant="destructive" title="حذف الإعلان" onClick={() => deleteListing.mutate({ listingId: item.id })}><Trash2 className="h-4 w-4" /></Button></>}</div></div>{editing !== item.id && <div className="mt-3 flex flex-wrap gap-2"><Button size="sm" onClick={() => moderateListing.mutate({ listingId: item.id, status: 'Published' })}>نشر</Button><Button size="sm" variant="outline" onClick={() => moderateListing.mutate({ listingId: item.id, status: 'Rejected' })}>رفض المحتوى</Button></div>}</div>) || <Empty text="لا توجد إعلانات." />}</CardContent></Card></TabsContent>
        <TabsContent value="finance" className="mt-4 grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2"><CircleDollarSign className="h-5 w-5 text-amber-600" />العمولة والتسويات</CardTitle></CardHeader><CardContent><form className="flex items-end gap-3" onSubmit={event => { event.preventDefault(); const value = Number(rate); if (value < 0 || value > 30) return toast.error('أدخل نسبة بين 0 و30'); updateCommission.mutate({ commissionRateBasisPoints: Math.round(value * 100) }); }}><label className="flex-1 text-sm font-semibold">نسبة العمولة (%)<input className="mt-2 w-full rounded-lg border p-3" type="number" min="0" max="30" step="0.1" value={rate} onChange={event => setRate(event.target.value)} /></label><Button type="submit">حفظ</Button></form><div className="mt-5 grid grid-cols-2 gap-3"><Metric label="إجمالي التحصيل" value={money(stats?.grossRevenue || 0)} /><Metric label="مستحقات الوكالات" value={money((stats?.grossRevenue || 0) - (stats?.platformFees || 0))} /><Metric label="المدفوعات" value={String(payments.data?.length || 0)} /><Metric label="طلبات السحب" value={String(payouts.data?.length || 0)} /></div></CardContent></Card><Card><CardHeader><CardTitle>آخر المعاملات</CardTitle></CardHeader><CardContent className="space-y-3">{payments.data?.slice(0, 8).map(item => <div key={item.id} className="flex items-center justify-between border-b pb-3 text-sm last:border-0"><span>{money(item.amount)}<small className="mr-2 block text-xs text-slate-500">#{item.bookingId} · {item.method}</small></span><Badge variant={item.status === 'Succeeded' ? 'default' : 'secondary'}>{item.status}</Badge></div>) || <Empty text="لا توجد معاملات." />}</CardContent></Card></TabsContent>
        <TabsContent value="settings" className="mt-4"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Settings2 className="h-5 w-5 text-emerald-600" />هوية وتشغيل المنصة</CardTitle></CardHeader><CardContent><form className="grid gap-4 sm:grid-cols-2" onSubmit={event => { event.preventDefault(); updateSettings.mutate(platformForm); }}><Field label="اسم المنصة" value={platformForm.platformName} onChange={value => setPlatformForm({ ...platformForm, platformName: value })} /><Field label="بريد التواصل" value={platformForm.contactEmail} onChange={value => setPlatformForm({ ...platformForm, contactEmail: value })} type="email" /><Field label="هاتف التواصل" value={platformForm.contactPhone} onChange={value => setPlatformForm({ ...platformForm, contactPhone: value })} /><label className="flex items-center gap-3 rounded-lg border p-3 text-sm font-semibold"><input type="checkbox" checked={platformForm.maintenanceMode} onChange={event => setPlatformForm({ ...platformForm, maintenanceMode: event.target.checked })} />وضع الصيانة</label><Button className="w-fit sm:col-span-2" type="submit">حفظ الإعدادات</Button></form></CardContent></Card></TabsContent>
        <TabsContent value="audit" className="mt-4"><Card><CardHeader><CardTitle className="flex items-center gap-2"><LockKeyhole className="h-5 w-5 text-emerald-600" />سجل الأمان والتدقيق</CardTitle></CardHeader><CardContent className="space-y-1">{auditLogs.data?.map(item => <ActivityRow key={item.id} action={item.action} detail={`${item.entityType}${item.entityId ? ` #${item.entityId}` : ''} · بواسطة ${item.actorName || item.actorId}`} date={item.createdAt} />) || <Empty text="لا توجد أحداث تدقيق." />}</CardContent></Card></TabsContent>
      </Tabs>
    </div>
  </main>;
}

function Tab({ value, icon: Icon, children }: { value: string; icon: typeof Activity; children: React.ReactNode }) { return <TabsTrigger value={value} className="gap-2 text-slate-600 data-[state=active]:bg-[#102d2b] data-[state=active]:text-white"><Icon className="h-4 w-4" />{children}</TabsTrigger>; }
function Empty({ text }: { text: string }) { return <div className="grid min-h-24 place-items-center text-sm text-slate-400">{text}</div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-slate-50 p-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 font-black text-[#102d2b]">{value}</p></div>; }
function Field({ label, value, onChange, type = 'text' }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <label className="text-sm font-semibold">{label}<input className="mt-2 w-full rounded-lg border p-3 font-normal" type={type} value={value} onChange={event => onChange(event.target.value)} /></label>; }
function ActivityRow({ action, detail, date }: { action: string; detail: string; date: Date }) { return <div className="flex items-start gap-3 border-b py-3 last:border-0"><span className="mt-1 rounded-full bg-emerald-50 p-1.5 text-emerald-600"><ShieldAlert className="h-3.5 w-3.5" /></span><div className="min-w-0 flex-1"><p className="text-sm font-bold">{action}</p><p className="text-xs text-slate-500">{detail}</p></div><time className="whitespace-nowrap text-[10px] text-slate-400">{new Date(date).toLocaleDateString('ar-MA')}</time></div>; }
