import { createContext, ReactNode, useContext, useEffect, useMemo, useState } from "react";
import { readBrandPreference, writeBrandPreference } from "@/config/brand";

export type Language = "ar" | "fr" | "en";

export const SUPPORTED_LANGUAGES: Language[] = ["ar", "fr", "en"];

export function getDirectionForLanguage(language: Language): "rtl" | "ltr" {
  return language === "ar" ? "rtl" : "ltr";
}

export function getLocaleForLanguage(language: Language): string {
  if (language === "ar") return "ar-MA";
  if (language === "fr") return "fr-MA";
  return "en-GB";
}

interface LanguageContextType {
  language: Language;
  direction: "rtl" | "ltr";
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  ar: {
    searchCityOdgency: "اختر المدينة أو الوكالة",
    search: "بحث",
    advancedFilters: "فلاتر متقدمة",
    resetFilters: "إعادة تعيين الفلاتر",
    naturalSearch: "البحث الطبيعي",
    searchPlaceholder: "ابحث عن سيارة أو عقار أو مكتب...",
    sector: "القطاع",
    allSectors: "جميع القطاعات",
    carsOnly: "السيارات فقط",
    propertiesOnly: "العقارات فقط",
    officeOnly: "المكاتب فقط",
    officeType: "نوع المكتب",
    privateOffice: "مكتب خاص",
    coworking: "مساحة مشتركة",
    meetingRoom: "قاعة اجتماعات",
    companyHeadquarters: "مقر شركة",
    rentalType: "مدة الكراء",
    daily: "يومي",
    monthly: "شهري",
    yearly: "سنوي",
    amenities: "المرافق",
    fiber: "ألياف بصرية",
    airConditioning: "تكييف هواء",
    parking: "موقف سيارات",
    reception: "استقبال",
    maxPrice: "الحد الأقصى للسعر",
    offersFoundPrefix: "تم العثور على",
    availableOffers: "عروض متاحة",
    sortBy: "ترتيب حسب",
    lowestPrice: "السعر الأقل أولاً",
    highestPrice: "السعر الأعلى أولاً",
    listingsLoadErrorTitle: "تعذر تحميل الإعلانات",
    noMatchingListings: "لا توجد نتائج مطابقة",
    noMatchingListingsDesc: "جرّب تعديل الفلاتر أو البحث في مدينة أخرى.",
    cityCasablanca: "الدار البيضاء",
    cityAgadir: "تأجير في أكادير",
    cityMarrakech: "تأجير في مراكش",
    cityCasablancaFooter: "تأجير في الدار البيضاء",
    cityTangier: "تأجير في طنجة",
    cityRabat: "تأجير في الرباط",
    footerNoticeText: "جميع الحقوق محفوظة للمنصة",
    footerAddress: "المغرب",
    heroBadge: "المنصة الأولى لكراء السيارات والعقارات بالمغرب",
    heroTitlePrefix: "اكتشف أفضل عروض",
    heroTitleCars: "السيارات",
    heroTitleProperties: "والعقارات",
    heroTitleSuffix: "",
    heroDescription: "قارن وحجز بسهولة تامة وبأفضل الأسعار عبر مختلف المدن المغربية.",
    heroReviewButton: "تقييمات العملاء",
    searchTabProperties: "العقارات",
    searchTabCars: "السيارات",
    searchDropoffDate: "تاريخ الاسترجاع",
    searchPickupDate: "تاريخ الاستلام",
    searchSubmitAdvanced: "بحث متقدم",
    popularCarBrandsTitle: "أبرز العلامات التجارية للسيارات",
    propertyTypesTitle: "أنواع العقارات المطلوبة",
    bentoBadge: "تجربة متكاملة",
    bentoTitle: "احجز سيارتك بكل أمان",
    bentoSubtitle: "نحن نوفر لك أفضل الخيارات الموثوقة بالمغرب مع ضمان الجودة والسرعة.",
    bentoRealEstateTitle: "عقارات استثنائية للإقامة والاستثمار",
    bentoRealEstateDescription: "استكشف أرقى الفلل والشقق المجهزة بأفضل المواصفات.",
    browsePropertiesAvailable: "تصفح العقارات المتاحة",
    viewAllListings: "عرض كل الإعلانات",
    blogBadge: "المدونة",
    blogTitle: "أحدث المقالات والدلائل السياحية",
    blogTravelGuideTag: "دليل السفر",
    blogCard1Title: "دليلك الشامل لكراء السيارات في الدار البيضاء ومراكش",
    blogCard1Description: "تعرف على أهم النصائح القانونية والتقنية لتأجير السيارات بكل أمان في المدن الكبرى بالمغرب.",
    blogDrivingTipsTag: "نصائح القيادة",
    blogCard3Title: "أهم نصائح القيادة الآمنة في الطرق السيّارة المغربية",
    blogCard3Description: "دليلك الشامل لتجربة قيادة مريحة وخالية من المخاطر.",
    readMore: "اقرأ المزيد",
    blogPropInvestmentTag: "استثمار عقاري",
    blogCard2Title: "لماذا يُعد الاستثمار العقاري في مراكش الأفضل حالياً؟",
    blogCard2Description: "تحليل شامل لفرص العائد الاستثماري المرتفع.",
    browseAllArticles: "تصفح جميع المقالات",
    faqBadge: "الأسئلة الشائعة",
    faqTitle: "كل ما تحتاج معرفته قبل الحجز",
    faqSubtitle: "إجابات واضحة عن أبرز الاستفسارات المتعلقة بعملية الحجز والدفع.",
    faqCategoryBooking: "الحجز",
    faqCategorySecurity: "الأمان",
    faqCategoryPartners: "الشركاء",
    faqCategoryCancellation: "الإلغاء",
    faqQuestion1: "كيف أحجز سيارة أو عقار؟",
    faqAnswer1: "اختر المدينة والتواريخ ثم اضغط على البحث للعثور على أفضل العروض.",
    faqQuestion2: "هل بياناتي المالية محمية؟",
    faqAnswer2: "نعم، نستخدم تشفير SSL ونتعاون مع CMI لضمان أمان جميع المعاملات.",
    faqQuestion3: "من هم شركاء المنصة؟",
    faqAnswer3: "شركاؤنا هم وكلاء تأجير السيارات المرخصة ومالكو العقارات في جميع المدن المغربية.",
    faqQuestion4: "هل يمكنني إلغاء حجزي؟",
    faqAnswer4: "نعم، يمكنك الإلغاء خلال 24 ساعة من تأكيد الحجز.",
    trustTitle3: "دعم فني على مدار الساعة",
    trustDesc3: "فريق خدمة العملاء جاهز لمساعدتك طوال أيام الأسبوع.",
    trustTitle2: "أسعار شفافة بدون رسوم خفية",
    trustDesc2: "ندفعك لتدفع القيمة الحقيقية بكل وضوح وأمان.",
    trustTitle1: "حجوزات مضمونة وآمنة",
    trustDesc1: "نضمن لك حجزاً آمناً مع شركاء موثوقين في جميع المدن المغربية.",
    home: "الرئيسية",
    cars: "السيارات",
    properties: "العقارات",
    partnerPortal: "فضاء الشركاء",
    partnerJoinTitle: "كن شريكاً في ALTUSplace",
    partnerJoinSubtitle: "سجّل وكالتك الآن لإدارة سياراتك ومكاتبك عبر حسابك الخاص، أو ادخل إلى لوحة تحكم وكالتك إن كنت شريكاً حالياً.",
    partnerRegisterNew: "تسجيل وكالة جديدة",
    partnerExistingLogin: "تسجيل الدخول للوكلاء الحاليين",
    partnerExistingDesc: "إذا كانت لديك وكالة مسجّلة مسبقاً على المنصة، سجّل الدخول للوصول إلى لوحة تحكم وكالتك الخاصة بحجوزاتك وعروضك وأرباحك.",
    partnerGoToDashboard: "الدخول إلى لوحة تحكم وكالتي",
    admin: "الإدارة",
    dashboard: "لوحة التحكم",
    myBookings: "حجوزاتي",
    help: "المساعدة",
    blog: "المدونة",
    close: "إغلاق",
    language: "اللغة",
    currency: "العملة",
    arabic: "العربية",
    french: "الفرنسية",
    english: "الإنجليزية",
    mainNavLabel: "التنقل الرئيسي",
    mobileNavLabel: "التنقل المحمول",
    openMenuLabel: "فتح القائمة",
    closeMenuLabel: "إغلاق القائمة",
    openSearchLabel: "فتح البحث",
    searchTitleLabel: "عنوان البحث",
    loadingPage: "جاري تحميل الصفحة...",
    accessChecking: "جاري التحقق من صلاحية الوصول...",
    loginRequired: "تسجيل الدخول مطلوب",
    loginRequiredDesc: "يرجى تسجيل الدخول للوصول إلى هذه الصفحة",
    loginAction: "تسجيل الدخول",
    accountInactive: "الحساب غير نشط",
    accountInactiveDesc: "حسابك غير نشط حالياً. يرجى التواصل مع الدعم.",
    forbiddenTitle: "الوصول مرفوض",
    forbiddenDesc: "ليس لديك صلاحية للوصول إلى هذه الصفحة",
    loginToFollowNotifications: "سجّل الدخول لمتابعة الإشعارات والتنبيهات",
    accountSecurity: "أمان الحساب",
    securityTwoFactor: "المصادقة الثنائية",
    kycTitle: "التحقق من الهوية",
    kycSubtitle: "نحتاج للتحقق من هويتك لضمان أمان المعاملات",
    identityVerification: "أوافق على التحقق من هويتي وفقاً لسياسة المنصة",
    loading: "جاري التحميل...",
    back: "رجوع",
    listingsLoadError: "تعذر تحميل الإعلانات",
    bookNow: "احجز الآن",
    continue: "متابعة",
    viewDetails: "عرض التفاصيل",
    publishedPrice: "السعر المنشور",
    noImage: "لا توجد صورة",
    noVerifiedReviews: "لا توجد تقييمات موثقة",
    listingCategoryProperty: "عقار",
    listingCategoryCar: "سيارة",
    providerNamePlaceholder: "مزود الخدمة",
    transmissionAutomatic: "أوتوماتيك",
    fuelDieselPetrol: "ديزل/بنزين",
    heroTitle: "بوابتك الموثوقة لكراء السيارات في المغرب",
    heroTitleAnd: "و",
    termsOfService: "شروط الاستخدام",
    privacyPolicy: "سياسة الخصوصية",
    readTermsAndAgree: "اقرأ الشروط ووافق عليها",
    toggleThemeLabel: "تبديل المظهر (فاتح/داكن)",
    themeToDarkToast: "تم تفعيل المظهر الداكن",
    themeToLightToast: "تم تفعيل المظهر الفاتح",
    commentsTitle: "التعليقات والأسئلة",
    commentsSubtitle: "اطرح أسئلتك وشارك تجربتك حول هذا العرض مع المجتمع.",
    commentsCountSuffix: "تعليقًا",
    noComments: "لا توجد تعليقات بعد — كن أول من يشارك بسؤال أو تجربة.",
    commentsLoadError: "تعذر تحميل التعليقات حالياً. حاول مرة أخرى لاحقاً.",
    commentRetry: "إعادة المحاولة",
    commentsLoading: "جاري تحميل التعليقات...",
    writeCommentPlaceholder: "اكتب سؤالك أو تعليقك...",
    postComment: "نشر التعليق",
    postingComment: "جاري النشر...",
    commentReply: "رد",
    replyPlaceholder: "اكتب ردك...",
    cancelReply: "إلغاء الرد",
    deleteComment: "حذف",
    deleteCommentConfirm: "هل أنت متأكد من حذف هذا التعليق؟",
    commentDeleted: "تم حذف التعليق.",
    commentPosted: "تم نشر تعليقك.",
    loginToComment: "سجّل الدخول للمشاركة في التعليقات",
    loginToCommentDesc: "التعليقات متاحة لكل المستخدمين المسجلين.",
    loadMoreComments: "عرض المزيد من التعليقات",
    commentAuthorYou: "أنت",
    commentAuthorAnonymous: "مستخدم",
    mapResultsTitle: "نتائج البحث في هذه المنطقة",
    searchRadius: "نصف قطر البحث",
    mapResultsCountSuffix: "نتيجة",
    mapNoResults: "لا توجد نتائج في المنطقة المعروضة. جرّب تكبير نطاق البحث أو تحريك الخريطة.",
    mapViewListing: "عرض",
    mapDragHint: "ابحث وحرّك الخريطة — النتائج تتحدث تلقائياً",
    mapRadiusLabel: "نصف قطر البحث:",
    mapKmUnit: "كم",
    all: "الكل",
    city: "المدينة",
    price: "السعر",
    searchPropertyLocation: "موقع العقار",
    searchPropertyType: "نوع العقار",
    propTypeApartment: "شقة",
    propTypeVilla: "فيلا",
    propTypeStudio: "استوديو",
    searchMaxPrice: "الحد الأقصى للسعر",
    maxPriceUnder1000: "أقل من 1000 درهم",
    maxPriceUnder2500: "أقل من 2500 درهم",
    maxPriceUnder5000: "أقل من 5000 درهم",
    maxPriceOver5000: "أكثر من 5000 درهم",
    catAll: "الكل",
    catSuv: "دفع رباعي",
    catSedan: "سيدان",
    catApartment: "شقق",
    catVilla: "فيلات",
    catStudio: "استوديو",
    browseCategories: "تصفح حسب الفئة",
    sortRecommended: "الأنسب",
    sortRating: "الأعلى تقييماً",
    bentoFleetTitle: "أسطول سيارات متنوع",
    bentoFleetDescription: "سيدان اقتصادية، سيارات رباعية الدفع وعائلية — كلها مؤمّنة وجاهزة للانطلاق إلى أي مدينة مغربية.",
    browseCarsAvailable: "تصفح السيارات المتاحة",
    featuredListingsBadge: "عروض مختارة",
    featuredListingsTitle: "إعلانات مميزة",
    marrakechDistricts: "مراكش",
    casablancaDistricts: "الدار البيضاء",
    tangierDistricts: "طنجة",
    rabatDistricts: "الرباط",
    whatsappChat: "محادثة واتساب",
    whatsappChatLabel: "تواصل مباشرة عبر واتساب",
  },
  fr: {
    searchCityOdgency: "Ville ou agence",
    search: "Recherche",
    advancedFilters: "Filtres avancés",
    resetFilters: "Réinitialiser les filtres",
    naturalSearch: "Recherche naturelle",
    searchPlaceholder: "Recherchez une voiture, un bien, un bureau...",
    sector: "Secteur",
    allSectors: "Tous les secteurs",
    carsOnly: "Voitures uniquement",
    propertiesOnly: "Biens immobiliers uniquement",
    officeOnly: "Bureaux uniquement",
    officeType: "Type de bureau",
    privateOffice: "Bureau privé",
    coworking: "Coworking",
    meetingRoom: "Salle de réunion",
    companyHeadquarters: "Siège d'entreprise",
    rentalType: "Durée de location",
    daily: "Journalier",
    monthly: "Mensuel",
    yearly: "Annuel",
    amenities: "Équipements",
    fiber: "Fibre optique",
    airConditioning: "Climatisation",
    parking: "Parking",
    reception: "Accueil",
    maxPrice: "Prix maximum",
    offersFoundPrefix: "Résultats :",
    availableOffers: "offre(s) disponible(s)",
    sortBy: "Trier par",
    lowestPrice: "Prix croissant",
    highestPrice: "Prix décroissant",
    listingsLoadErrorTitle: "Impossible de charger les annonces",
    noMatchingListings: "Aucune annonce correspondante",
    noMatchingListingsDesc: "Essayez d'ajuster les filtres ou de chercher dans une autre ville.",
    cityCasablanca: "Casablanca",
    cityAgadir: "Louer à Agadir",
    cityMarrakech: "Louer à Marrakech",
    cityCasablancaFooter: "Louer à Casablanca",
    cityTangier: "Louer à Tanger",
    cityRabat: "Louer à Rabat",
    footerNoticeText: "Tous droits réservés",
    footerAddress: "Maroc",
    heroBadge: "La première plateforme de location au Maroc",
    heroTitlePrefix: "Découvrez les meilleures offres de",
    heroTitleCars: "Voitures",
    heroTitleProperties: "et Immobiliers",
    heroTitleSuffix: "",
    heroDescription: "Comparez et réservez facilement aux meilleurs prix dans toutes les villes marocaines.",
    heroReviewButton: "Avis clients",
    searchTabProperties: "Immobilier",
    searchTabCars: "Voitures",
    searchDropoffDate: "Date de retour",
    searchPickupDate: "Date de départ",
    searchSubmitAdvanced: "Recherche avancée",
    popularCarBrandsTitle: "Marques de voitures populaires",
    propertyTypesTitle: "Types de propriétés",
    bentoBadge: "Expérience complète",
    bentoTitle: "Réservez votre voiture en toute sécurité",
    bentoSubtitle: "Nous vous offrons les meilleures options fiables au Maroc.",
    bentoRealEstateTitle: "Propriétés exceptionnelles",
    bentoRealEstateDescription: "Découvrez les plus belles villas et appartements.",
    browsePropertiesAvailable: "Parcourir les propriétés",
    viewAllListings: "Voir toutes les annonces",
    blogBadge: "Blog",
    blogTitle: "Articles récents et guides de voyage",
    blogTravelGuideTag: "Guide de voyage",
    blogCard1Title: "Le guide ultime pour louer une voiture à Casablanca et Marrakech",
    blogCard1Description: "Découvrez les meilleures astuces pour louer une voiture en toute sécurité dans les grandes villes du Maroc.",
    blogDrivingTipsTag: "Conseils de conduite",
    blogCard3Title: "Conseils de conduite sécurisée au Maroc",
    blogCard3Description: "Votre guide complet pour une conduite sans risque.",
    readMore: "Lire la suite",
    blogPropInvestmentTag: "Investissement",
    blogCard2Title: "Pourquoi investir dans l'immobilier à Marrakech ?",
    blogCard2Description: "Analyse des opportunités de rendement.",
    browseAllArticles: "Tous les articles",
    faqBadge: "FAQ",
    faqTitle: "Questions Fréquentes",
    faqSubtitle: "Réponses claires à vos questions de réservation.",
    trustTitle3: "Support 24/7",
    trustDesc3: "Notre équipe est prête à vous aider.",
    trustTitle2: "Prix transparents",
    trustDesc2: "Aucun frais caché pour vos réservations.",
    trustTitle1: "Réservations garanties et sécurisées",
    trustDesc1: "Nous vous garantissons une réservation sécurisée avec des partenaires de confiance.",
    home: "Accueil",
    cars: "Voitures",
    properties: "Immobilier",
    partnerPortal: "Espace Partenaires",
    partnerJoinTitle: "Devenez partenaire d'ALTUSplace",
    partnerJoinSubtitle: "Inscrivez votre agence dès maintenant pour gérer vos véhicules et vos bureaux depuis votre compte, ou connectez-vous au tableau de bord de votre agence si vous êtes déjà partenaire.",
    partnerRegisterNew: "Inscrire une nouvelle agence",
    partnerExistingLogin: "Connexion des partenaires existants",
    partnerExistingDesc: "Si votre agence est déjà inscrite sur la plateforme, connectez-vous pour accéder au tableau de bord dédié à vos réservations, annonces et revenus.",
    partnerGoToDashboard: "Accéder au tableau de bord de mon agence",
    admin: "Administration",
    dashboard: "Tableau de bord",
    myBookings: "Mes réservations",
    help: "Aide",
    blog: "Blog",
    close: "Fermer",
    language: "Langue",
    currency: "Devise",
    arabic: "Arabe",
    french: "Français",
    english: "Anglais",
    mainNavLabel: "Navigation principale",
    mobileNavLabel: "Navigation mobile",
    openMenuLabel: "Ouvrir le menu",
    closeMenuLabel: "Fermer le menu",
    openSearchLabel: "Ouvrir la recherche",
    searchTitleLabel: "Titre de recherche",
    loadingPage: "Chargement de la page...",
    accessChecking: "Vérification des droits d'accès...",
    loginRequired: "Connexion requise",
    loginRequiredDesc: "Veuillez vous connecter pour accéder à cette page",
    loginAction: "Se connecter",
    accountInactive: "Compte inactif",
    accountInactiveDesc: "Votre compte est actuellement inactif. Veuillez contacter le support.",
    forbiddenTitle: "Accès interdit",
    forbiddenDesc: "Vous n'avez pas la permission d'accéder à cette page",
    loginToFollowNotifications: "Connectez-vous pour suivre vos notifications",
    accountSecurity: "Sécurité du compte",
    securityTwoFactor: "Authentification à deux facteurs",
    kycTitle: "Vérification d'identité",
    kycSubtitle: "Nous devons vérifier votre identité pour garantir la sécurité des transactions",
    identityVerification: "J'accepte la vérification de mon identité conformément à la politique de la plateforme",
    loading: "Chargement...",
    back: "Retour",
    listingsLoadError: "Impossible de charger les annonces",
    bookNow: "Réserver maintenant",
    continue: "Continuer",
    viewDetails: "Voir les détails",
    publishedPrice: "Prix publié",
    noImage: "Aucune image disponible",
    noVerifiedReviews: "Aucun avis vérifié",
    listingCategoryProperty: "Bien immobilier",
    listingCategoryCar: "Voiture",
    providerNamePlaceholder: "Prestataire",
    transmissionAutomatic: "Automatique",
    fuelDieselPetrol: "Diesel/Essence",
    rentalConditions: "Conditions de location",
    minDriverAge: "Âge minimum",
    securityDeposit: "Caution",
    madUnit: "MAD",
    kmPerDay: "km/jour",
    dailyMileageLimit: "Limite quotidienne de kilométrage",
    rentalTermsNote: "Veuillez lire attentivement les conditions de location avant de finaliser la réservation",
    madPerDay: "MAD/jour",
    madPerMonth: "MAD/mois",
    madPerYear: "MAD/an",
    madPerNight: "MAD/nuit",
    detailsAndBooking: "Détails et réservation",
    smartBadge: "Recommandations intelligentes",
    smartTitle: "Offres sélectionnées pour vous",
    smartSourceBadge: "Analyse intelligente",
    smartReasonFavorite: "De vos favoris",
    smartReasonCity: "Dans votre ville",
    smartReasonNewListing: "Nouvelle annonce",
    cmiPayment: "Paiement électronique (CMI)",
    cmiPaymentMobile: "Paiement via CMI",
    currencySwitched: "Devise changée en",
    notifications: "Notifications",
    notificationsTitle: "Centre de notifications",
    notificationsPanelLabel: "Panneau de notifications",
    notificationsWithUnread: "notifications non lues",
    noNotifications: "Aucune notification",
    viewAllNotifications: "Voir toutes les notifications",
    markAllRead: "Tout marquer comme lu",
    markingAllRead: "Marquage en cours...",
    markAllReadSuccess: "Toutes les notifications marquées comme lues",
    whatsappNotify: "Notification envoyée via WhatsApp",
    toggleThemeLabel: "Changer de thème",
    themeToDarkToast: "Thème sombre activé",
    themeToLightToast: "Thème clair activé",
    soundOnLabel: "Son activé",
    soundOffLabel: "Son désactivé",
    soundEnabledLabel: "Activer le son",
    soundDisabledLabel: "Désactiver le son",
    switchedToArabic: "Langue changée en Arabe",
    switchedToEnglish: "Langue changée en Anglais",
    switchedToFrench: "Langue changée en Français",
    faqCategoryBooking: "Réservation",
    faqCategorySecurity: "Sécurité",
    faqCategoryPartners: "Partenaires",
    faqCategoryCancellation: "Annulation",
    faqQuestion1: "Comment réserver une voiture ou un bien ?",
    faqAnswer1: "Choisissez la ville et les dates, puis cliquez sur rechercher pour trouver les meilleures offres.",
    faqQuestion2: "Mes données financières sont-elles protégées ?",
    faqAnswer2: "Oui, nous utilisons le cryptage SSL et collaborons avec le CMI pour garantir la sécurité.",
    faqQuestion3: "Qui sont les partenaires de la plateforme ?",
    faqAnswer3: "Nos partenaires sont des agences de location de voitures et des propriétaires immobiliers agréés.",
    faqQuestion4: "Puis-je annuler ma réservation ?",
    faqAnswer4: "Oui, vous pouvez annuler dans les 24 heures suivant la confirmation.",
    addCar: "Ajouter une voiture",
    heroTitle: "Votre porte d'entrée de confiance pour la location de voitures au Maroc",
    heroTitleAnd: "et",
    termsOfService: "Conditions d'utilisation",
    privacyPolicy: "Politique de confidentialité",
    readTermsAndAgree: "Lire et accepter les conditions",
    commentsTitle: "Commentaires et questions",
    commentsSubtitle: "Posez vos questions et partagez votre avis sur cette annonce.",
    commentsCountSuffix: "commentaires",
    noComments: "Aucun commentaire pour le moment — soyez le premier à participer.",
    commentsLoadError: "Impossible de charger les commentaires. Réessayez plus tard.",
    commentRetry: "Réessayer",
    commentsLoading: "Chargement des commentaires...",
    writeCommentPlaceholder: "Rédigez votre question ou votre commentaire...",
    postComment: "Publier",
    postingComment: "Publication en cours...",
    commentReply: "Répondre",
    replyPlaceholder: "Rédigez votre réponse...",
    cancelReply: "Annuler",
    deleteComment: "Supprimer",
    deleteCommentConfirm: "Confirmer la suppression de ce commentaire ?",
    commentDeleted: "Commentaire supprimé.",
    commentPosted: "Votre commentaire a été publié.",
    loginToComment: "Connectez-vous pour commenter",
    loginToCommentDesc: "Les commentaires sont ouverts à tous les utilisateurs connectés.",
    loadMoreComments: "Voir plus de commentaires",
    commentAuthorYou: "Vous",
    commentAuthorAnonymous: "Utilisateur",
    mapResultsTitle: "Résultats dans cette zone",
    searchRadius: "Rayon de recherche",
    mapResultsCountSuffix: "résultat(s)",
    mapNoResults: "Aucun résultat dans la zone affichée. Élargissez le rayon ou déplacez la carte.",
    mapViewListing: "Voir",
    mapDragHint: "Déplacez la carte — les résultats se mettent à jour automatiquement",
    mapRadiusLabel: "Rayon de recherche :",
    mapKmUnit: "km",
    all: "Tous",
    city: "Ville",
    price: "Prix",
    searchPropertyLocation: "Localisation du bien",
    searchPropertyType: "Type de bien",
    propTypeApartment: "Appartement",
    propTypeVilla: "Villa",
    propTypeStudio: "Studio",
    searchMaxPrice: "Prix maximum",
    maxPriceUnder1000: "Moins de 1000 MAD",
    maxPriceUnder2500: "Moins de 2500 MAD",
    maxPriceUnder5000: "Moins de 5000 MAD",
    maxPriceOver5000: "Plus de 5000 MAD",
    catAll: "Tous",
    catSuv: "SUV",
    catSedan: "Berlines",
    catApartment: "Appartements",
    catVilla: "Villas",
    catStudio: "Studios",
    browseCategories: "Parcourir par catégorie",
    sortRecommended: "Recommandés",
    sortRating: "Mieux notés",
    bentoFleetTitle: "Une flotte variée",
    bentoFleetDescription: "Berlines économiques, SUV et familiales — toutes assurées et prêtes à partir vers n'importe quelle ville marocaine.",
    browseCarsAvailable: "Parcourir les voitures disponibles",
    featuredListingsBadge: "Sélection",
    featuredListingsTitle: "Annonces en vedette",
    marrakechDistricts: "Marrakech",
    casablancaDistricts: "Casablanca",
    tangierDistricts: "Tanger",
    rabatDistricts: "Rabat",
    whatsappChat: "Chat WhatsApp",
    whatsappChatLabel: "Discuter directement sur WhatsApp",
  },
  en: {
    searchCityOdgency: "City or Agency",
    search: "Search",
    advancedFilters: "Advanced filters",
    resetFilters: "Reset filters",
    naturalSearch: "Natural search",
    searchPlaceholder: "Search for a car, property, office...",
    sector: "Sector",
    allSectors: "All sectors",
    carsOnly: "Cars only",
    propertiesOnly: "Properties only",
    officeOnly: "Offices only",
    officeType: "Office type",
    privateOffice: "Private office",
    coworking: "Coworking",
    meetingRoom: "Meeting room",
    companyHeadquarters: "Company headquarters",
    rentalType: "Rental period",
    daily: "Daily",
    monthly: "Monthly",
    yearly: "Yearly",
    amenities: "Amenities",
    fiber: "Fiber optic",
    airConditioning: "Air conditioning",
    parking: "Parking",
    reception: "Reception desk",
    maxPrice: "Max price",
    offersFoundPrefix: "Found",
    availableOffers: "available offers",
    sortBy: "Sort by",
    lowestPrice: "Lowest price",
    highestPrice: "Highest price",
    listingsLoadErrorTitle: "Failed to load listings",
    noMatchingListings: "No matching listings",
    noMatchingListingsDesc: "Try adjusting your filters or searching in another city.",
    cityCasablanca: "Casablanca",
    cityAgadir: "Rent in Agadir",
    cityMarrakech: "Rent in Marrakech",
    cityCasablancaFooter: "Rent in Casablanca",
    cityTangier: "Rent in Tanger",
    cityRabat: "Rent in Rabat",
    footerNoticeText: "All rights reserved",
    footerAddress: "Morocco",
    heroBadge: "The leading rental platform in Morocco",
    heroTitlePrefix: "Discover the best offers for",
    heroTitleCars: "Cars",
    heroTitleProperties: "and Properties",
    heroTitleSuffix: "",
    heroDescription: "Compare and book easily at the best prices across various Moroccan cities.",
    heroReviewButton: "Customer Reviews",
    searchTabProperties: "Properties",
    searchTabCars: "Cars",
    searchDropoffDate: "Drop-off Date",
    searchPickupDate: "Pick-up Date",
    searchSubmitAdvanced: "Advanced Search",
    popularCarBrandsTitle: "Popular Car Brands",
    propertyTypesTitle: "Property Types",
    bentoBadge: "Complete Experience",
    bentoTitle: "Book your car securely",
    bentoSubtitle: "We provide the best reliable options in Morocco.",
    bentoRealEstateTitle: "Exceptional Properties",
    bentoRealEstateDescription: "Explore luxury villas and apartments.",
    browsePropertiesAvailable: "Browse Available Properties",
    viewAllListings: "View All Listings",
    blogBadge: "Blog",
    blogTitle: "Latest Articles & Travel Guides",
    blogTravelGuideTag: "Travel Guide",
    blogCard1Title: "The complete guide to renting a car in Casablanca and Marrakech",
    blogCard1Description: "Learn the essential legal and practical tips to rent a car safely across Morocco's major cities.",
    blogDrivingTipsTag: "Driving Tips",
    blogCard3Title: "Safe driving tips on Moroccan highways",
    blogCard3Description: "Your ultimate guide for a smooth journey.",
    readMore: "Read More",
    blogPropInvestmentTag: "Real Estate",
    blogCard2Title: "Why real estate investment in Marrakech is top",
    blogCard2Description: "Comprehensive analysis of high ROI opportunities.",
    browseAllArticles: "Browse All Articles",
    faqBadge: "FAQ",
    faqTitle: "Frequently Asked Questions",
    faqSubtitle: "Clear answers to your booking questions.",
    trustTitle3: "24/7 Support",
    trustDesc3: "Our customer service team is ready to help.",
    trustTitle2: "Transparent Pricing",
    trustDesc2: "No hidden fees, pay true value.",
    trustTitle1: "Guaranteed and secure bookings",
    trustDesc1: "We guarantee you a secure booking with trusted partners in all Moroccan cities.",
    home: "Home",
    cars: "Cars",
    properties: "Properties",
    partnerPortal: "Partner Portal",
    partnerJoinTitle: "Become an ALTUSplace partner",
    partnerJoinSubtitle: "Register your agency now to manage your vehicles and offices from your own account, or sign in to your agency dashboard if you are already a partner.",
    partnerRegisterNew: "Register a new agency",
    partnerExistingLogin: "Existing Partner Login",
    partnerExistingDesc: "If your agency is already registered on the platform, sign in to access the dashboard dedicated to your bookings, listings and earnings.",
    partnerGoToDashboard: "Go to my agency dashboard",
    admin: "Admin",
    dashboard: "Dashboard",
    myBookings: "My Bookings",
    help: "Help",
    blog: "Blog",
    close: "Close",
    language: "Language",
    currency: "Currency",
    arabic: "Arabic",
    french: "French",
    english: "English",
    mainNavLabel: "Main navigation",
    mobileNavLabel: "Mobile navigation",
    openMenuLabel: "Open menu",
    closeMenuLabel: "Close menu",
    openSearchLabel: "Open search",
    searchTitleLabel: "Search title",
    loadingPage: "Loading page...",
    accessChecking: "Checking access permissions...",
    loginRequired: "Login required",
    loginRequiredDesc: "Please log in to access this page",
    loginAction: "Log in",
    accountInactive: "Account inactive",
    accountInactiveDesc: "Your account is currently inactive. Please contact support.",
    forbiddenTitle: "Access forbidden",
    forbiddenDesc: "You do not have permission to access this page",
    loginToFollowNotifications: "Log in to follow your notifications",
    accountSecurity: "Account security",
    securityTwoFactor: "Two-factor authentication",
    kycTitle: "Identity verification",
    kycSubtitle: "We need to verify your identity to ensure transaction security",
    identityVerification: "I agree to identity verification according to platform policy",
    loading: "Loading...",
    back: "Back",
    listingsLoadError: "Failed to load listings",
    bookNow: "Book now",
    continue: "Continue",
    viewDetails: "View details",
    publishedPrice: "Published price",
    noImage: "No image available",
    noVerifiedReviews: "No verified reviews",
    listingCategoryProperty: "Property",
    listingCategoryCar: "Car",
    providerNamePlaceholder: "Service provider",
    transmissionAutomatic: "Automatic",
    fuelDieselPetrol: "Diesel/Petrol",
    rentalConditions: "Rental conditions",
    minDriverAge: "Minimum age",
    securityDeposit: "Security deposit",
    madUnit: "MAD",
    kmPerDay: "km/day",
    dailyMileageLimit: "Daily mileage limit",
    rentalTermsNote: "Please read the rental conditions carefully before finalizing the booking",
    madPerDay: "MAD/day",
    madPerMonth: "MAD/month",
    madPerYear: "MAD/year",
    madPerNight: "MAD/night",
    detailsAndBooking: "Details and booking",
    smartBadge: "Smart recommendations",
    smartTitle: "Offers selected for you",
    smartSourceBadge: "Smart analysis",
    smartReasonFavorite: "From your favorites",
    smartReasonCity: "In your city",
    smartReasonNewListing: "New listing",
    cmiPayment: "Electronic payment (CMI)",
    cmiPaymentMobile: "Payment via CMI",
    currencySwitched: "Currency changed to",
    notifications: "Notifications",
    notificationsTitle: "Notifications center",
    notificationsPanelLabel: "Notifications panel",
    notificationsWithUnread: "unread notifications",
    noNotifications: "No notifications",
    viewAllNotifications: "View all notifications",
    markAllRead: "Mark all as read",
    markingAllRead: "Marking all as read...",
    markAllReadSuccess: "All notifications marked as read",
    whatsappNotify: "Notification sent via WhatsApp",
    toggleThemeLabel: "Toggle theme",
    themeToDarkToast: "Switched to dark theme",
    themeToLightToast: "Switched to light theme",
    soundOnLabel: "Sound on",
    soundOffLabel: "Sound off",
    soundEnabledLabel: "Enable sound",
    soundDisabledLabel: "Disable sound",
    switchedToArabic: "Switched to Arabic",
    switchedToEnglish: "Switched to English",
    switchedToFrench: "Switched to French",
    faqCategoryBooking: "Booking",
    faqCategorySecurity: "Security",
    faqCategoryPartners: "Partners",
    faqCategoryCancellation: "Cancellation",
    faqQuestion1: "How do I book a car or property?",
    faqAnswer1: "Choose the city and dates, then click search to find the best offers.",
    faqQuestion2: "Is my financial data protected?",
    faqAnswer2: "Yes, we use SSL encryption and partner with CMI to ensure all transactions are secure.",
    faqQuestion3: "Who are the platform partners?",
    faqAnswer3: "Our partners are licensed car rental agencies and property owners in all Moroccan cities.",
    faqQuestion4: "Can I cancel my booking?",
    faqAnswer4: "Yes, you can cancel within 24 hours of confirmation.",
    addCar: "Add a car",
    heroTitle: "Your trusted gateway to car rentals in Morocco",
    heroTitleAnd: "and",
    termsOfService: "Terms of service",
    privacyPolicy: "Privacy policy",
    readTermsAndAgree: "Read and accept the terms",
    commentsTitle: "Comments & questions",
    commentsSubtitle: "Ask questions and share your feedback about this listing.",
    commentsCountSuffix: "comments",
    noComments: "No comments yet — be the first to ask or share.",
    commentsLoadError: "Failed to load comments. Please try again later.",
    commentRetry: "Retry",
    commentsLoading: "Loading comments...",
    writeCommentPlaceholder: "Write your question or comment...",
    postComment: "Post",
    postingComment: "Posting...",
    commentReply: "Reply",
    replyPlaceholder: "Write a reply...",
    cancelReply: "Cancel",
    deleteComment: "Delete",
    deleteCommentConfirm: "Delete this comment?",
    commentDeleted: "Comment deleted.",
    commentPosted: "Your comment was posted.",
    loginToComment: "Log in to join the discussion",
    loginToCommentDesc: "Comments are open to all signed-in users.",
    loadMoreComments: "Load more comments",
    commentAuthorYou: "You",
    commentAuthorAnonymous: "User",
    mapResultsTitle: "Results in this area",
    searchRadius: "Search radius",
    mapResultsCountSuffix: "result(s)",
    mapNoResults: "No results in the visible area. Widen the radius or move the map.",
    mapViewListing: "View",
    mapDragHint: "Move the map — results update automatically",
    mapRadiusLabel: "Search radius:",
    mapKmUnit: "km",
    all: "All",
    city: "City",
    price: "Price",
    searchPropertyLocation: "Property location",
    searchPropertyType: "Property type",
    propTypeApartment: "Apartment",
    propTypeVilla: "Villa",
    propTypeStudio: "Studio",
    searchMaxPrice: "Max price",
    maxPriceUnder1000: "Under 1000 MAD",
    maxPriceUnder2500: "Under 2500 MAD",
    maxPriceUnder5000: "Under 5000 MAD",
    maxPriceOver5000: "Over 5000 MAD",
    catAll: "All",
    catSuv: "SUVs",
    catSedan: "Sedans",
    catApartment: "Apartments",
    catVilla: "Villas",
    catStudio: "Studios",
    browseCategories: "Browse by category",
    sortRecommended: "Recommended",
    sortRating: "Top rated",
    bentoFleetTitle: "A diverse car fleet",
    bentoFleetDescription: "Economy sedans, SUVs and family cars — all insured and ready to hit any Moroccan road.",
    browseCarsAvailable: "Browse available cars",
    featuredListingsBadge: "Featured",
    featuredListingsTitle: "Featured listings",
    marrakechDistricts: "Marrakech",
    casablancaDistricts: "Casablanca",
    tangierDistricts: "Tanger",
    rabatDistricts: "Rabat",
    whatsappChat: "WhatsApp chat",
    whatsappChatLabel: "Chat directly on WhatsApp",
  },
};

export function getTranslation(language: Language, key: string): string {
  return translations[language]?.[key] ?? translations["en"]?.[key] ?? translations["ar"]?.[key] ?? key;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("ar");

  useEffect(() => {
    const savedLanguage = readBrandPreference("language");
    if (savedLanguage && ["ar", "fr", "en"].includes(savedLanguage)) {
      setLanguageState(savedLanguage as Language);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    writeBrandPreference("language", lang);
  };

  const direction = getDirectionForLanguage(language);

  useEffect(() => {
    document.documentElement.dir = direction;
    document.documentElement.lang = language;
  }, [direction, language]);

  const t = (key: string): string => {
    return getTranslation(language, key);
  };

  const value = useMemo(() => ({ language, direction, setLanguage, t }), [language, direction]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}