import { createContext, ReactNode, useContext, useEffect, useMemo, useState } from "react";
import { readBrandPreference, writeBrandPreference } from "@/config/brand";

export type Language = "ar" | "fr" | "en";

interface LanguageContextType {
  language: Language;
  direction: "rtl" | "ltr";
  setLanguage: (language: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

export const translations: Record<Language, Record<string, string>> = {
  ar: {
    home: "الرئيسية",
    cars: "تأجير السيارات",
    properties: "العقارات",
    search: "البحث والعروض",
    admin: "لوحة الإدارة",
    dashboard: "لوحة الوكالة",
    addCar: "إضافة إعلان",
    myBookings: "حجوزاتي",
    favorites: "المفضلة",
    profile: "الملف الشخصي",
    help: "الدعم والمساعدة",
    about: "عن المنصة",
    blog: "المدونة",
    notifications: "الإشعارات",
    kyc: "التحقق من الهوية",
    heroTitle: "بوابتك الموثوقة لحجز السيارات والعقارات في المغرب",
    heroSubtitle: "اكتشف عروضاً مختارة من وكالات موثوقة، واحجز بسهولة مع عقود رقمية وفوترة شفافة.",
    aiSearchPlaceholder: "مثال: أريد سيارة دفع رباعي في أكادير أو شقة فاخرة في مراكش...",
    searchNow: "ابحث الآن",
    bookNow: "احجز الآن",
    viewDetails: "عرض التفاصيل",
    city: "المدينة",
    propertyType: "نوع العقار",
    price: "السعر",
    dates: "التواريخ",
    language: "اللغة",
    currency: "العملة",
    chooseLanguage: "اختيار اللغة",
    arabic: "العربية",
    french: "Français",
    english: "English",
    switchArabic: "التبديل إلى العربية",
    switchFrench: "Passer au français",
    cmiPayment: "الدفع عبر CMI",
    bankTransfer: "التحويل البنكي",
    invoice: "الفاتورة",
    vat: "TVA",
    kycTitle: "تحقق من هويتك بأمان",
    kycSubtitle: "ارفع بطاقة التعريف الوطنية أو رخصة القيادة أو السجل التجاري ليتمكن فريقنا من مراجعة حسابك.",
    cni: "بطاقة التعريف الوطنية",
    drivingLicense: "رخصة القيادة",
    commercialRegister: "السجل التجاري",
    submitDocument: "إرسال الوثيقة للمراجعة",
    pendingReview: "قيد المراجعة",
    approved: "تم التحقق",
    rejected: "مرفوضة",
    verified: "تم التحقق",
    unverified: "غير موثق",
    selectFile: "اختر ملفاً",
    noFile: "لم يتم اختيار ملف",
    maxFile: "PDF أو JPG أو PNG، بحد أقصى 8 ميغابايت",
    identityVerification: "التحقق من الهوية",
    uploadDocument: "رفع وثيقة",
    drivingLicenseRecommended: "يُنصح برخصة القيادة لحجوزات السيارات.",
    nationalIdRecommended: "يُنصح ببطاقة التعريف الوطنية لحجوزات العقارات.",
    filesEncrypted: "يتم تشفير ملفاتك وحصر الوصول إليها للإدارة فقط",
    save: "حفظ",
    cancel: "إلغاء",
    close: "إغلاق",
    back: "رجوع",
    loading: "جاري التحميل...",
    allRights: "جميع الحقوق محفوظة",
    terms: "الشروط",
    privacy: "الخصوصية",
    rentalConditions: "شروط الكراء",
    minDriverAge: "الحد الأدنى لسن السائق",
    securityDeposit: "ضمان مسترجع",
    dailyMileageLimit: "حد الكيلومترات اليومي",
    kmPerDay: "كم / يوم",
    madUnit: "درهم",
    rentalTermsNote: "تنطبق هذه الشروط القياسية على جميع السيارات، ويبقى العقد الموقّع عند الاستلام هو المرجع النهائي؛ الكيلومترات الإضافية تُحاسب وفق العقد.",
    termsOfService: "شروط الاستخدام",
    readTermsAndAgree: "قراءة الشروط والموافقة عليها",
    officeSpaces: "مساحات الأعمال",
    officeType: "نوع المساحة",
    privateOffice: "مكتب مستقل",
    coworking: "مساحة عمل مشتركة",
    meetingRoom: "قاعة اجتماعات",
    companyHeadquarters: "مقر شركة",
    rentalType: "نوع الكراء",
    daily: "يومي",
    monthly: "شهري",
    yearly: "سنوي",
    amenities: "التجهيزات والخدمات",
    fiber: "إنترنت Fiber Optic",
    airConditioning: "مكيف هواء",
    reception: "قاعة استقبال",
    parking: "مرآب Parking",
    security: "حراسة",
    all: "الكل",
    resultsFound: "عرض متاح",
    officeOnly: "المكاتب فقط",
    allSectors: "كل القطاعات",
    detailsAndBooking: "التفاصيل والحجز",
    resetFilters: "إعادة ضبط",
    advancedFilters: "تصفية متقدمة",
    naturalSearch: "بحث ذكي باللغة الطبيعية",
    searchPlaceholder: "ابحث عما ترغب به...",
    sector: "القطاع",
    carsOnly: "السيارات فقط",
    propertiesOnly: "العقارات فقط",
    maxPrice: "السعر الأقصى",
    allCities: "جميع المدن",
    offersFoundPrefix: "تم العثور على",
    sortBy: "الترتيب حسب",
    lowestPrice: "السعر: من الأرخص للأغلى",
    highestPrice: "السعر: من الأغلى للأرخص",
    loadingListings: "جاري تحميل العروض",
    listingsLoadError: "تعذر تحميل العروض حالياً. يرجى المحاولة مرة أخرى بعد قليل.",
    noMatchingListings: "لا توجد عروض مطابقة للفلاتر الحالية. جرّب توسيع المدينة أو السعر أو نوع المكتب.",
    showMap: "عرض الخريطة التفاعلية",
    hideMap: "إخفاء الخريطة التفاعلية",
    availableOffers: "عرض متاح",

    // ─── Home: Hero & Search Bar ───
    heroBadge: "منصة الوساطة الأولى المعتمدة بين المزودين والزبائن في المغرب",
    heroTitlePrefix: "بوابتك الموثوقة لحجز",
    heroTitleCars: "السيارات",
    heroTitleAnd: "و",
    heroTitleProperties: "العقارات",
    heroTitleSuffix: "بكل أمان",
    heroDescription: "ALTUSplace منصة وسيطة ذكية تربطك بأرقى شركات كراء السيارات والوكالات العقارية المستقلة عبر المدن المغربية، مع عقود رقمية وتوقيع إلكتروني فوري.",
    heroReviewButton: "عرض مراجعة الأعمال 2025",
    searchTabCars: "بحث عن السيارات",
    searchTabProperties: "بحث عن العقارات",
    searchCityOrAgency: "المدينة أو الوكالة",
    searchPickupDate: "تاريخ الاستلام",
    searchDropoffDate: "تاريخ التسليم",
    searchPropertyLocation: "المنطقة / المدينة",
    searchPropertyType: "نوع العقار",
    searchMaxPrice: "الحد الأقصى للسعر (درهم/ليلة)",
    searchSubmitAdvanced: "بحث متقدم وعرض النتائج الفورية",
    cityCasablanca: "الدار البيضاء",
    cityMarrakech: "مراكش",
    cityAgadir: "أغادير",
    cityTangier: "طنجة",
    cityRabat: "الرباط",
    marrakechDistricts: "مراكش (جيليز، النخيل)",
    casablancaDistricts: "الدار البيضاء (أنفا، المعاريف)",
    tangierDistricts: "طنجة (كورنيش، مالاباطا)",
    rabatDistricts: "الرباط (أكدال، السويسي)",
    propTypeApartment: "شقة فاخرة",
    propTypeVilla: "فيلا بمسبح",
    propTypeStudio: "استوديو مودرن",
    maxPriceUnder1000: "أقل من 1000 درهم",
    maxPriceUnder2500: "أقل من 2500 درهم",
    maxPriceUnder5000: "أقل من 5000 درهم",
    maxPriceOver5000: "أكثر من 5000 درهم",
    popularCarBrandsTitle: "أشهر ماركات السيارات العالمية المتوفرة في المنصة",
    propertyTypesTitle: "أنواع العقارات والفلل والشقق المتاحة للإيجار",
    brandCarCount: "{{count}}+ سيارة",
    brandPropertyCount: "{{count}}+ عقار",
    propLuxuryVillas: "فلل فاخرة بمسبح",
    propModernApartments: "شقق مودرن",
    propCornichePenthouses: "بنتهاوس كورنيش",
    propBusinessStudios: "استوديوهات رجال الأعمال",
    propSecureResidences: "إقامات محروسة",

    // ─── Home: Bento Grid ───
    bentoBadge: "تصميم هندسي متطور",
    bentoTitle: "استكشف الأقسام الرئيسية",
    bentoSubtitle: "اختر ما بين أسطول السيارات الفاخرة أو العقارات الحصرية مع ضمانات حماية كاملة.",
    bentoFleetTitle: "أسطول السيارات الفاخرة والاقتصادية",
    bentoFleetDescription: "أحدث موديلات سيارات الدفع الرباعي، السيارات العائلية، والسيارات الرياضية في الدار البيضاء، مراكش، طنجة وأغادير مع توصيل مجاني.",
    browseCarsAvailable: "تصفح السيارات المتاحة",
    bentoRealEstateTitle: "العقارات والشقق الفاخرة",
    bentoRealEstateDescription: "شقق مودرن مطلة على الكورنيش وفيلات خاصة بمسبح في أرقى الأحياء السكنية.",
    browsePropertiesAvailable: "تصفح العقارات",

    // ─── Home: Featured Listings ───
    listingCategoryProperty: "عقار",
    listingCategoryCar: "سيارة",
    providerNamePlaceholder: "بيانات الإعلان من ALTUSplace",
    featuredListingsBadge: "إعلانات متاحة للتصفح",
    featuredListingsTitle: "إعلانات مختارة من المنصة",
    viewAllListings: "عرض كافة الإعلانات ({{count}})",
    dailyPrice: "السعر اليومي",
    transmissionAutomatic: "أوتوماتيك",
    fuelDieselPetrol: "ديزل / بنزين",

    // ─── Home: Blog ───
    blogBadge: "مدونة المنصة",
    blogTitle: "أحدث المقالات والنصائح العقارية والسياحية",
    browseAllArticles: "تصفح جميع المقالات",
    readMore: "اقرأ المزيد",
    blogTravelGuideTag: "دليل السفر",
    blogCard1Title: "دليلك الشامل لكراء السيارات في الدار البيضاء ومراكش 2026",
    blogCard1Description: "تعرف على أهم النصائح القانونية والتقنية لتأجير السيارات بكل أمان في المدن الكبرى بالمغرب.",
    blogPropInvestmentTag: "استثمار عقاري",
    blogCard2Title: "أفضل المناطق الاستثمارية العقارية في طنجة وأغادير",
    blogCard2Description: "استعراض لأهم الأحياء المطلة على البحر والتي تشهد إقبالاً كبيراً من السياح والمستثمرين.",
    blogDrivingTipsTag: "نصائح قيادة",
    blogCard3Title: "كيف تختار السيارة المناسبة لرحلتك العائلية عبر الطرق السيارة؟",
    blogCard3Description: "مقارنة شاملة بين سيارات الـ SUV والاقتصادية والفاخرة لضمان أقصى درجات الراحة والأمان.",

    // ─── Home: Trust Banner ───
    trustTitle1: "حماية ودفع آمن 100%",
    trustDesc1: "بوابات دفع معتمدة وعقود رقمية مختومة قانونياً.",
    trustTitle2: "وكالات معتمدة وموثوقة",
    trustDesc2: "مراجعة وتدقيق دوري لجميع شركائنا في المغرب.",
    trustTitle3: "دعم فني على مدار الساعة",
    trustDesc3: "فريق خدمة عملاء متواجد دائماً لمساعدتك.",

    // ─── FAQ ───
    faqBadge: "الأسئلة المتكررة",
    faqTitle: "كل ما ترغب في معرفته حول خدمات ALTUSplace",
    faqSubtitle: "إجابات شاملة وواضحة عن عمليات الحجز والدفع وحقوق الشركاء والزبناء في المغرب.",
    faqCategoryBooking: "التأجير والحجوزات",
    faqQuestion1: "كيف يمكنني حجز سيارة أو عقار عبر منصة ALTUSplace؟",
    faqAnswer1: "يمكنك بكل سهولة تصفح السيارات أو العقارات المتاحة، اختيار تواريخ الاستلام والتسليم، ثم الضغط على 'احجز الآن'. سيتم توجيهك لملء تفاصيل الحجز وإتمام الدفع الآمن لعربون الضمان عبر بواباتنا المعتمدة.",
    faqCategorySecurity: "الأمان والضمان",
    faqQuestion2: "هل المعاملات المالية وعربون الحجز آمنان؟",
    faqAnswer2: "نعم تماماً. تعتمد منصة ALTUSplace نظام ضمان مالي (Escrow) حيث تبقى أموال العربون في حساب الوسيط المعتمد حتى يتم تأكيد استلام السيارة أو العقار بحالة ممتازة من طرف الشريك.",
    faqCategoryPartners: "الشركاء والوكالات",
    faqQuestion3: "كيف يمكنني تسجيل شركتي أو عقاري كشريك في المنصة؟",
    faqAnswer3: "يمكنك الانتقال إلى صفحة 'لوحة الوكلاء' واختيار التسجيل كشركة كراء سيارات أو منعش عقاري، رفع وثائق التحقق (السجل التجاري أو البطاقة الوطنية)، وبعد مراجعة الإدارة سيتم تفعيل حسابك فوراً.",
    faqCategoryCancellation: "سياسة الإلغاء",
    faqQuestion4: "ما هي سياسة إلغاء الحجوزات واسترداد العربون؟",
    faqAnswer4: "يمكنك إلغاء الحجز مجاناً قبل موعد الاستلام بـ 48 ساعة واسترداد كامل العربون المدفوع. للإلغاء المتأخر، يتم تطبيق شروط الوكالة المتعاقد معها والموضحة في العقد الرقمي.",

    // ─── Smart recommendations ───
    smartBadge: "اقتراحات مخصصة",
    smartTitle: "عروض منشورة قد تناسب اهتمامك",
    smartSourceBadge: "مبنية على سجل التصفح المحلي",
    smartReasonFavorite: "مشابه لما حفظته في المفضلة",
    smartReasonCity: "في المدينة التي تصفحتها: {{city}}",
    smartReasonNewListing: "من الإعلانات المنشورة المتاحة",
    noImage: "لا توجد صورة",
    noVerifiedReviews: "لا توجد تقييمات موثقة",
    publishedPrice: "السعر المنشور",
    madPerDay: "درهم / يوم",
    madPerNight: "درهم / ليلة",
    madPerMonth: "درهم / شهر",
    madPerYear: "درهم / سنة",

    // ─── Footer ───
    footerAddress: "المغرب - الدار البيضاء، مراكش، أغادير، طنجة، الرباط",
    footerNoticeLabel: "بنود حماية المنصة",
    footerNoticeText: "المنصة وسيط تقني وإعلاني فقط ولا تملك أو تدير السيارات أو العقارات. يتحمل الشريك مسؤولية الحالة الميكانيكية والسلامة والنظافة ومطابقة الأصل للوصف، وتخضع العلاقة النهائية للعقد المكتوب عند الاستلام. تظهر شروط الرسوم والإلغاء قبل الدفع، وتُراجع حالات إخلال الشريك عبر مركز النزاعات وفق القانون المغربي.",
    footerTagline: "منصة تأجير السيارات والعقارات الأولى في المغرب.",

    // ─── Navbar / Global UI ───
    mainNavLabel: "التنقل الرئيسي",
    mobileNavLabel: "التنقل على الهاتف",
    chooseCurrency: "اختيار العملة",
    currencySwitched: "تم تبديل العملة بنجاح إلى {{currency}}",
    switchedToArabic: "تم التبديل إلى اللغة العربية",
    switchedToFrench: "Passé au français avec succès",
    switchedToEnglish: "Switched to English successfully",
    securityTwoFactor: "إدارة الأمان والمصادقة الثنائية",
    cmiPortal: "فتح بوابة الدفع CMI",
    whatsappNotify: "فتح إشعار واتساب",
    notificationsWithUnread: "الإشعارات، {{count}} غير مقروءة",
    notificationsTitle: "الإشعارات والتحديثات",
    notificationsPanelLabel: "قائمة الإشعارات",
    soundOffLabel: "إيقاف صوت الإشعارات",
    soundOnLabel: "تفعيل صوت الإشعارات",
    soundEnabledLabel: "الصوت مفعّل",
    soundDisabledLabel: "الصوت متوقف",
    markAllRead: "تحديد الكل كمقروء",
    markingAllRead: "جارٍ التحديث…",
    markAllReadSuccess: "تم تحديد جميع الإشعارات كمقروءة",
    loginToFollowNotifications: "سجّل الدخول لمتابعة إشعارات حجوزاتك.",
    noNotifications: "لا توجد إشعارات جديدة.",
    viewAllNotifications: "عرض كل الإشعارات",
    themeToLightToast: "تم تفعيل الوضع النهاري",
    themeToDarkToast: "تم تفعيل الوضع الليلي",
    toggleThemeLabel: "تبديل الوضع الليلي",
    openSearchLabel: "فتح البحث",
    searchTitleLabel: "البحث",
    openMenuLabel: "فتح القائمة",
    closeMenuLabel: "إغلاق القائمة",
    accountSecurity: "أمان الحساب",
    cmiPaymentMobile: "الدفع CMI",

    // ─── App / routing ───
    loadingPage: "جاري تحميل الصفحة...",
    accessChecking: "جاري التحقق من الصلاحيات...",
    loginRequired: "يلزم تسجيل الدخول",
    loginRequiredDesc: "سجّل الدخول للوصول إلى هذه اللوحة.",
    loginAction: "تسجيل الدخول",
    accountInactive: "الحساب غير نشط",
    accountInactiveDesc: "تم تعليق أو حظر هذا الحساب. تواصل مع الدعم للمراجعة.",
    forbiddenTitle: "403 — الوصول غير مسموح",
    forbiddenDesc: "ليس لديك الصلاحية لفتح هذه اللوحة.",
  },
  fr: {
    home: "Accueil",
    cars: "Location de voitures",
    properties: "Immobilier",
    search: "Recherche et offres",
    admin: "Administration",
    dashboard: "Tableau de bord agence",
    addCar: "Ajouter une annonce",
    myBookings: "Mes réservations",
    favorites: "Favoris",
    profile: "Profil",
    help: "Aide et support",
    about: "À propos",
    blog: "Blog",
    notifications: "Notifications",
    kyc: "Vérification d'identité",
    heroTitle: "Votre passerelle de confiance pour louer voitures et biens au Maroc",
    heroSubtitle: "Découvrez des offres sélectionnées auprès d'agences fiables, réservez simplement avec contrats numériques et facturation transparente.",
    aiSearchPlaceholder: "Exemple : je veux un SUV à Agadir ou un appartement de luxe à Marrakech...",
    searchNow: "Rechercher",
    bookNow: "Réserver maintenant",
    viewDetails: "Voir les détails",
    city: "Ville",
    propertyType: "Type de bien",
    price: "Prix",
    dates: "Dates",
    language: "Langue",
    currency: "Devise",
    chooseLanguage: "Choisir la langue",
    arabic: "العربية",
    french: "Français",
    english: "English",
    switchArabic: "التبديل إلى العربية",
    switchFrench: "Passer au français",
    cmiPayment: "Paiement CMI",
    bankTransfer: "Virement bancaire",
    invoice: "Facture",
    vat: "TVA",
    kycTitle: "Vérifiez votre identité en toute sécurité",
    kycSubtitle: "Téléversez votre CNI, permis de conduire ou registre de commerce pour permettre à notre équipe de vérifier votre compte.",
    cni: "Carte nationale d'identité",
    drivingLicense: "Permis de conduire",
    commercialRegister: "Registre de commerce",
    submitDocument: "Envoyer le document pour vérification",
    pendingReview: "En cours de vérification",
    approved: "Identité vérifiée",
    rejected: "Document refusé",
    verified: "Vérifié",
    unverified: "Non vérifié",
    selectFile: "Choisir un fichier",
    noFile: "Aucun fichier sélectionné",
    maxFile: "PDF, JPG ou PNG, 8 Mo maximum",
    identityVerification: "Vérification d'identité",
    uploadDocument: "Télécharger",
    drivingLicenseRecommended: "Le permis de conduite est recommandé pour les locations de voitures.",
    nationalIdRecommended: "La carte nationale d'identité est recommandée pour les locations immobilières.",
    filesEncrypted: "Vos fichiers sont cryptés et l'accès est restreint à l'administration uniquement.",
    save: "Enregistrer",
    cancel: "Annuler",
    close: "Fermer",
    back: "Retour",
    loading: "Chargement...",
    allRights: "Tous droits réservés",
    terms: "Conditions",
    privacy: "Confidentialité",
    rentalConditions: "Conditions de location",
    minDriverAge: "Âge minimum du conducteur",
    securityDeposit: "Caution remboursable",
    dailyMileageLimit: "Kilométrage quotidien inclus",
    kmPerDay: "km / jour",
    madUnit: "MAD",
    rentalTermsNote: "Ces conditions standard s'appliquent à toutes les voitures ; le contrat signé à la remise reste la référence finale. Les kilomètres supplémentaires sont facturés selon le contrat.",
    termsOfService: "Conditions d'utilisation",
    readTermsAndAgree: "Lire et accepter les conditions",
    officeSpaces: "Espaces professionnels",
    officeType: "Type d'espace",
    privateOffice: "Bureau indépendant",
    coworking: "Espace coworking",
    meetingRoom: "Salle de réunion",
    companyHeadquarters: "Siège d'entreprise",
    rentalType: "Type de location",
    daily: "Journalier",
    monthly: "Mensuel",
    yearly: "Annuel",
    amenities: "Équipements et services",
    fiber: "Internet Fiber Optic",
    airConditioning: "Climatisation",
    reception: "Accueil",
    parking: "Parking",
    security: "Sécurité",
    all: "Tous",
    resultsFound: "offre(s) disponible(s)",
    officeOnly: "Bureaux uniquement",
    allSectors: "Tous les secteurs",
    detailsAndBooking: "Détails et réservation",
    resetFilters: "Réinitialiser",
    advancedFilters: "Filtres avancés",
    naturalSearch: "Recherche intelligente en langage naturel",
    searchPlaceholder: "Recherchez ce dont vous avez besoin...",
    sector: "Secteur",
    carsOnly: "Voitures uniquement",
    propertiesOnly: "Biens uniquement",
    maxPrice: "Prix maximum",
    allCities: "Toutes les villes",
    offersFoundPrefix: "Résultat :",
    sortBy: "Trier par",
    lowestPrice: "Prix : du moins cher au plus cher",
    highestPrice: "Prix : du plus cher au moins cher",
    loadingListings: "Chargement des offres",
    listingsLoadError: "Les offres sont momentanément indisponibles. Veuillez réessayer.",
    noMatchingListings: "Aucune offre ne correspond aux filtres actuels. Élargissez la ville, le prix ou le type de bureau.",
    showMap: "Afficher la carte interactive",
    hideMap: "Masquer la carte interactive",
    availableOffers: "offre(s) disponible(s)",

    // ─── Home : Hero & Barre de recherche ───
    heroBadge: "La première plateforme d'intermédiation agréée entre prestataires et clients au Maroc",
    heroTitlePrefix: "Votre passerelle de confiance pour louer",
    heroTitleCars: "des voitures",
    heroTitleAnd: "et",
    heroTitleProperties: "des biens immobiliers",
    heroTitleSuffix: "en toute sécurité",
    heroDescription: "ALTUSplace est une plateforme d'intermédiation intelligente qui vous connecte aux meilleures sociétés de location de voitures et aux agences immobilières indépendantes des villes marocaines, avec contrats numériques et signature électronique instantanée.",
    heroReviewButton: "Voir la revue d'activité 2025",
    searchTabCars: "Recherche de voitures",
    searchTabProperties: "Recherche de biens",
    searchCityOrAgency: "Ville ou agence",
    searchPickupDate: "Date de prise en charge",
    searchDropoffDate: "Date de restitution",
    searchPropertyLocation: "Quartier / ville",
    searchPropertyType: "Type de bien",
    searchMaxPrice: "Prix maximum (MAD/nuit)",
    searchSubmitAdvanced: "Recherche avancée et résultats instantanés",
    cityCasablanca: "Casablanca",
    cityMarrakech: "Marrakech",
    cityAgadir: "Agadir",
    cityTangier: "Tanger",
    cityRabat: "Rabat",
    marrakechDistricts: "Marrakech (Guéliz, Palmeraie)",
    casablancaDistricts: "Casablanca (Anfa, Maârif)",
    tangierDistricts: "Tanger (Corniche, Malabata)",
    rabatDistricts: "Rabat (Agdal, Souissi)",
    propTypeApartment: "Appartement de luxe",
    propTypeVilla: "Villa avec piscine",
    propTypeStudio: "Studio moderne",
    maxPriceUnder1000: "Moins de 1000 MAD",
    maxPriceUnder2500: "Moins de 2500 MAD",
    maxPriceUnder5000: "Moins de 5000 MAD",
    maxPriceOver5000: "Plus de 5000 MAD",
    popularCarBrandsTitle: "Les plus grandes marques automobiles disponibles sur la plateforme",
    propertyTypesTitle: "Types de biens, villas et appartements à louer",
    brandCarCount: "{{count}}+ voitures",
    brandPropertyCount: "{{count}}+ biens",
    propLuxuryVillas: "Villas de luxe avec piscine",
    propModernApartments: "Appartements modernes",
    propCornichePenthouses: "Penthouses de la corniche",
    propBusinessStudios: "Studios business",
    propSecureResidences: "Résidences sécurisées",

    // ─── Home : Grille Bento ───
    bentoBadge: "Conception moderne et soignée",
    bentoTitle: "Explorez nos sections principales",
    bentoSubtitle: "Choisissez entre une flotte de voitures de luxe ou des biens exclusifs, avec des garanties de protection complètes.",
    bentoFleetTitle: "Flotte de voitures de luxe et économiques",
    bentoFleetDescription: "Les derniers modèles de SUV, voitures familiales et sportives à Casablanca, Marrakech, Tanger et Agadir, avec livraison gratuite.",
    browseCarsAvailable: "Parcourir les voitures disponibles",
    bentoRealEstateTitle: "Immobilier et appartements de luxe",
    bentoRealEstateDescription: "Appartements modernes avec vue sur la corniche et villas privées avec piscine dans les plus beaux quartiers.",
    browsePropertiesAvailable: "Parcourir les biens immobiliers",

    // ─── Home : Annonces à la une ───
    listingCategoryProperty: "Bien",
    listingCategoryCar: "Voiture",
    providerNamePlaceholder: "Annonce publiée par ALTUSplace",
    featuredListingsBadge: "Annonces disponibles",
    featuredListingsTitle: "Annonces sélectionnées de la plateforme",
    viewAllListings: "Voir toutes les annonces ({{count}})",
    dailyPrice: "Prix journalier",
    transmissionAutomatic: "Automatique",
    fuelDieselPetrol: "Diesel / essence",

    // ─── Home : Blog ───
    blogBadge: "Blog de la plateforme",
    blogTitle: "Derniers articles et conseils immobilier et voyage",
    browseAllArticles: "Voir tous les articles",
    readMore: "Lire la suite",
    blogTravelGuideTag: "Guide voyage",
    blogCard1Title: "Votre guide complet de location de voitures à Casablanca et Marrakech 2026",
    blogCard1Description: "Découvrez les conseils juridiques et techniques essentiels pour louer une voiture en toute sécurité dans les grandes villes du Maroc.",
    blogPropInvestmentTag: "Investissement immobilier",
    blogCard2Title: "Les meilleures zones d'investissement immobilier à Tanger et Agadir",
    blogCard2Description: "Tour d'horizon des quartiers côtiers les plus prisés par les touristes et les investisseurs.",
    blogDrivingTipsTag: "Conseils de conduite",
    blogCard3Title: "Comment choisir la voiture idéale pour votre voyage familial ?",
    blogCard3Description: "Comparatif complet entre SUV, voitures économiques et premium pour un confort et une sécurité maximums.",

    // ─── Home : Bannière de confiance ───
    trustTitle1: "Protection et paiement 100% sécurisés",
    trustDesc1: "Passerelles de paiement agréées et contrats numériques légalement signés.",
    trustTitle2: "Agences agréées et de confiance",
    trustDesc2: "Vérification et audit réguliers de tous nos partenaires au Maroc.",
    trustTitle3: "Support technique 24h/24",
    trustDesc3: "Une équipe de service client à votre écoute en permanence.",

    // ─── FAQ ───
    faqBadge: "Questions fréquentes",
    faqTitle: "Tout ce que vous devez savoir sur les services ALTUSplace",
    faqSubtitle: "Des réponses complètes et claires sur les réservations, les paiements et les droits des partenaires et clients au Maroc.",
    faqCategoryBooking: "Location et réservations",
    faqQuestion1: "Comment réserver une voiture ou un bien sur ALTUSplace ?",
    faqAnswer1: "Il vous suffit de parcourir les voitures ou biens disponibles, de choisir vos dates de prise en charge et de restitution, puis de cliquer sur « Réserver maintenant ». Vous serez guidé pour remplir les détails de la réservation et effectuer le paiement sécurisé de l'acompte via nos passerelles agréées.",
    faqCategorySecurity: "Sécurité et garanties",
    faqQuestion2: "Les transactions financières et l'acompte de réservation sont-ils sûrs ?",
    faqAnswer2: "Oui, totalement. ALTUSplace s'appuie sur un système de garantie financière (Escrow) : les fonds de l'acompte restent sur le compte de l'intermédiaire agréé jusqu'à confirmation de la prise en charge de la voiture ou du bien en excellent état par le partenaire.",
    faqCategoryPartners: "Partenaires et agences",
    faqQuestion3: "Comment enregistrer mon entreprise ou mon bien en tant que partenaire ?",
    faqAnswer3: "Rendez-vous sur le « Tableau de bord agence » et choisissez de vous inscrire comme société de location de voitures ou promoteur immobilier, téléversez vos documents de vérification (registre de commerce ou carte nationale), et après examen par l'administration votre compte sera activé immédiatement.",
    faqCategoryCancellation: "Politique d'annulation",
    faqQuestion4: "Quelle est la politique d'annulation et de remboursement de l'acompte ?",
    faqAnswer4: "Vous pouvez annuler gratuitement jusqu'à 48 heures avant la prise en charge et obtenir le remboursement intégral de l'acompte. Pour les annulations tardives, les conditions de l'agence contractante s'appliquent, telles que précisées dans le contrat numérique.",

    // ─── Recommandations intelligentes ───
    smartBadge: "Suggestions personnalisées",
    smartTitle: "Des offres publiées qui pourraient vous intéresser",
    smartSourceBadge: "Basées sur votre historique de navigation local",
    smartReasonFavorite: "Similaire à vos favoris",
    smartReasonCity: "Dans la ville que vous avez consultée : {{city}}",
    smartReasonNewListing: "Parmi les annonces publiées disponibles",
    noImage: "Aucune image",
    noVerifiedReviews: "Aucun avis vérifié",
    publishedPrice: "Prix publié",
    madPerDay: "MAD / jour",
    madPerNight: "MAD / nuit",
    madPerMonth: "MAD / mois",
    madPerYear: "MAD / an",

    // ─── Pied de page ───
    footerAddress: "Maroc — Casablanca, Marrakech, Agadir, Tanger, Rabat",
    footerNoticeLabel: "Clauses de protection de la plateforme",
    footerNoticeText: "La plateforme est uniquement un intermédiaire technique et publicitaire ; elle ne possède ni ne gère les voitures ou les biens immobiliers. Le partenaire est responsable de l'état mécanique, de la sécurité, de la propreté et de la conformité du bien à la description ; la relation finale est régie par le contrat écrit à la remise. Les frais et les conditions d'annulation sont affichés avant le paiement, et les manquements des partenaires sont examinés via le centre de résolution des litiges conformément au droit marocain.",
    footerTagline: "La première plateforme de location de voitures et de biens immobiliers au Maroc.",

    // ─── Barre de navigation / UI globale ───
    mainNavLabel: "Navigation principale",
    mobileNavLabel: "Navigation mobile",
    chooseCurrency: "Choisir la devise",
    currencySwitched: "Devise changée avec succès en {{currency}}",
    switchedToArabic: "تم التبديل إلى اللغة العربية",
    switchedToFrench: "Passé au français avec succès",
    switchedToEnglish: "Switched to English successfully",
    securityTwoFactor: "Gérer la sécurité et l'authentification à deux facteurs",
    cmiPortal: "Ouvrir la passerelle de paiement CMI",
    whatsappNotify: "Ouvrir la notification WhatsApp",
    notificationsWithUnread: "Notifications, {{count}} non lue(s)",
    notificationsTitle: "Notifications et mises à jour",
    notificationsPanelLabel: "Liste des notifications",
    soundOffLabel: "Désactiver le son des notifications",
    soundOnLabel: "Activer le son des notifications",
    soundEnabledLabel: "Son activé",
    soundDisabledLabel: "Son coupé",
    markAllRead: "Tout marquer comme lu",
    markingAllRead: "Mise à jour…",
    markAllReadSuccess: "Toutes les notifications sont marquées comme lues",
    loginToFollowNotifications: "Connectez-vous pour suivre les notifications de vos réservations.",
    noNotifications: "Aucune nouvelle notification.",
    viewAllNotifications: "Voir toutes les notifications",
    themeToLightToast: "Mode clair activé",
    themeToDarkToast: "Mode sombre activé",
    toggleThemeLabel: "Basculer le mode sombre",
    openSearchLabel: "Ouvrir la recherche",
    searchTitleLabel: "Recherche",
    openMenuLabel: "Ouvrir le menu",
    closeMenuLabel: "Fermer le menu",
    accountSecurity: "Sécurité du compte",
    cmiPaymentMobile: "Paiement CMI",

    // ─── App / routage ───
    loadingPage: "Chargement de la page...",
    accessChecking: "Vérification des accès...",
    loginRequired: "Connexion requise",
    loginRequiredDesc: "Connectez-vous pour accéder à ce tableau de bord.",
    loginAction: "Se connecter",
    accountInactive: "Compte inactif",
    accountInactiveDesc: "Ce compte a été suspendu ou bloqué. Contactez le support pour un examen.",
    forbiddenTitle: "403 — Accès refusé",
    forbiddenDesc: "Vous n'êtes pas autorisé à ouvrir ce tableau de bord.",
  },
  en: {
    home: "Home",
    cars: "Car rentals",
    properties: "Properties",
    search: "Search & listings",
    admin: "Admin dashboard",
    dashboard: "Agency dashboard",
    addCar: "Add listing",
    myBookings: "My bookings",
    favorites: "Favorites",
    profile: "Profile",
    help: "Help & support",
    about: "About ALTUSplace",
    blog: "Blog",
    notifications: "Notifications",
    kyc: "Identity verification",
    heroTitle: "Your trusted gateway to car and property rentals in Morocco",
    heroSubtitle: "Discover carefully selected offers from trusted agencies, with easy booking, digital contracts, and transparent billing.",
    aiSearchPlaceholder: "Example: I want an SUV in Agadir or a luxury apartment in Marrakech...",
    searchNow: "Search now",
    bookNow: "Book now",
    viewDetails: "View details",
    city: "City",
    propertyType: "Property type",
    price: "Price",
    dates: "Dates",
    language: "Language",
    currency: "Currency",
    chooseLanguage: "Choose language",
    arabic: "العربية",
    french: "Français",
    english: "English",
    switchArabic: "Switch to Arabic",
    switchFrench: "Passer au français",
    cmiPayment: "CMI payment",
    bankTransfer: "Bank transfer",
    invoice: "Invoice",
    vat: "VAT",
    kycTitle: "Verify your identity securely",
    kycSubtitle: "Upload your national ID or commercial register so our team can review your account.",
    cni: "National identity card",
    drivingLicense: "Driver's license",
    commercialRegister: "Commercial register",
    submitDocument: "Submit document for review",
    pendingReview: "Under review",
    approved: "Verified",
    rejected: "Rejected",
    verified: "Verified",
    unverified: "Not verified",
    identityVerification: "Identity verification",
    uploadDocument: "Upload a document",
    drivingLicenseRecommended: "A driver's license is recommended for car rentals.",
    nationalIdRecommended: "The national identity card is recommended for property bookings.",
    filesEncrypted: "Your files are encrypted and access is restricted to administration only.",
    selectFile: "Choose a file",
    noFile: "No file selected",
    maxFile: "PDF, JPG, or PNG, up to 8 MB",
    save: "Save",
    cancel: "Cancel",
    close: "Close",
    back: "Back",
    loading: "Loading...",
    allRights: "All rights reserved",
    terms: "Terms",
    privacy: "Privacy",
    rentalConditions: "Rental conditions",
    minDriverAge: "Minimum driver age",
    securityDeposit: "Refundable deposit",
    dailyMileageLimit: "Included daily mileage",
    kmPerDay: "km / day",
    madUnit: "MAD",
    rentalTermsNote: "These standard conditions apply to all cars; the contract signed at pickup remains the final reference. Extra kilometers are billed according to the contract.",
    termsOfService: "Terms of service",
    readTermsAndAgree: "Read and accept the terms",
    officeSpaces: "Business spaces",
    officeType: "Space type",
    privateOffice: "Private office",
    coworking: "Coworking space",
    meetingRoom: "Meeting room",
    companyHeadquarters: "Company headquarters",
    rentalType: "Rental period",
    daily: "Daily",
    monthly: "Monthly",
    yearly: "Yearly",
    amenities: "Amenities and services",
    fiber: "Fiber optic internet",
    airConditioning: "Air conditioning",
    reception: "Reception",
    parking: "Parking",
    security: "Security",
    all: "All",
    resultsFound: "available offer(s)",
    officeOnly: "Offices only",
    allSectors: "All sectors",
    detailsAndBooking: "Details and booking",
    resetFilters: "Reset filters",
    advancedFilters: "Advanced filters",
    naturalSearch: "Natural-language search",
    searchPlaceholder: "Search for what you need...",
    sector: "Sector",
    carsOnly: "Cars only",
    propertiesOnly: "Properties only",
    maxPrice: "Maximum price",
    allCities: "All cities",
    offersFoundPrefix: "Found",
    sortBy: "Sort by",
    lowestPrice: "Price: low to high",
    highestPrice: "Price: high to low",
    loadingListings: "Loading listings",
    listingsLoadError: "Listings are temporarily unavailable. Please try again.",
    noMatchingListings: "No listings match the current filters. Try widening the city, price, or office type.",
    showMap: "Show interactive map",
    hideMap: "Hide interactive map",
    availableOffers: "available offer(s)",

    // ─── Home: Hero & Search Bar ───
    heroBadge: "Morocco's first trusted mediation platform connecting providers and customers",
    heroTitlePrefix: "Your trusted gateway to book",
    heroTitleCars: "cars",
    heroTitleAnd: "and",
    heroTitleProperties: "properties",
    heroTitleSuffix: "— safe and secure",
    heroDescription: "ALTUSplace is a smart intermediary platform connecting you to Morocco's finest car rental companies and independent real estate agencies, with digital contracts and instant e-signature.",
    heroReviewButton: "View 2025 business review",
    searchTabCars: "Search cars",
    searchTabProperties: "Search properties",
    searchCityOrAgency: "City or agency",
    searchPickupDate: "Pickup date",
    searchDropoffDate: "Return date",
    searchPropertyLocation: "Area / city",
    searchPropertyType: "Property type",
    searchMaxPrice: "Max price (MAD/night)",
    searchSubmitAdvanced: "Advanced search & instant results",
    cityCasablanca: "Casablanca",
    cityMarrakech: "Marrakech",
    cityAgadir: "Agadir",
    cityTangier: "Tangier",
    cityRabat: "Rabat",
    marrakechDistricts: "Marrakech (Guéliz, Palmeraie)",
    casablancaDistricts: "Casablanca (Anfa, Maârif)",
    tangierDistricts: "Tangier (Corniche, Malabata)",
    rabatDistricts: "Rabat (Agdal, Souissi)",
    propTypeApartment: "Luxury apartment",
    propTypeVilla: "Villa with pool",
    propTypeStudio: "Modern studio",
    maxPriceUnder1000: "Under 1000 MAD",
    maxPriceUnder2500: "Under 2500 MAD",
    maxPriceUnder5000: "Under 5000 MAD",
    maxPriceOver5000: "Over 5000 MAD",
    popularCarBrandsTitle: "Popular car brands available on the platform",
    propertyTypesTitle: "Property, villa & apartment types available for rent",
    brandCarCount: "{{count}}+ cars",
    brandPropertyCount: "{{count}}+ properties",
    propLuxuryVillas: "Luxury villas with pool",
    propModernApartments: "Modern apartments",
    propCornichePenthouses: "Corniche penthouses",
    propBusinessStudios: "Business studios",
    propSecureResidences: "Gated residences",

    // ─── Home: Bento Grid ───
    bentoBadge: "Modern & sleek design",
    bentoTitle: "Explore our main sections",
    bentoSubtitle: "Choose between a premium car fleet or exclusive properties, with full protection guarantees.",
    bentoFleetTitle: "Luxury & economy car fleet",
    bentoFleetDescription: "The latest SUVs, family cars, and sports cars in Casablanca, Marrakech, Tangier, and Agadir with free delivery.",
    browseCarsAvailable: "Browse available cars",
    bentoRealEstateTitle: "Luxury real estate & apartments",
    bentoRealEstateDescription: "Modern seafront apartments and private villas with pools in the most exclusive neighborhoods.",
    browsePropertiesAvailable: "Browse properties",

    // ─── Home: Featured Listings ───
    listingCategoryProperty: "Property",
    listingCategoryCar: "Car",
    providerNamePlaceholder: "Listing by ALTUSplace",
    featuredListingsBadge: "Available listings",
    featuredListingsTitle: "Hand-picked listings",
    viewAllListings: "View all listings ({{count}})",
    dailyPrice: "Daily price",
    transmissionAutomatic: "Automatic",
    fuelDieselPetrol: "Diesel / petrol",

    // ─── Home: Blog ───
    blogBadge: "Platform blog",
    blogTitle: "Latest articles & real-estate and travel tips",
    browseAllArticles: "Browse all articles",
    readMore: "Read more",
    blogTravelGuideTag: "Travel guide",
    blogCard1Title: "Your complete guide to car rentals in Casablanca & Marrakech 2026",
    blogCard1Description: "Learn the essential legal and practical tips for renting a car safely in Morocco's biggest cities.",
    blogPropInvestmentTag: "Property investment",
    blogCard2Title: "Best property investment areas in Tangier & Agadir",
    blogCard2Description: "An overview of the most sought-after seaside neighborhoods among tourists and investors.",
    blogDrivingTipsTag: "Driving tips",
    blogCard3Title: "How to choose the right car for your family road trip?",
    blogCard3Description: "A full comparison of SUVs, economy, and premium cars for maximum comfort and safety.",

    // ─── Home: Trust Banner ───
    trustTitle1: "100% secure payment protection",
    trustDesc1: "Approved payment gateways and legally sealed digital contracts.",
    trustTitle2: "Certified & trusted agencies",
    trustDesc2: "Regular review and auditing of all our partners in Morocco.",
    trustTitle3: "24/7 technical support",
    trustDesc3: "A customer service team always available to help.",

    // ─── FAQ ───
    faqBadge: "Frequently asked questions",
    faqTitle: "Everything you need to know about ALTUSplace",
    faqSubtitle: "Clear, comprehensive answers about bookings, payments, and partner and customer rights in Morocco.",
    faqCategoryBooking: "Rentals & bookings",
    faqQuestion1: "How can I book a car or property on ALTUSplace?",
    faqAnswer1: "Simply browse the available cars or properties, choose your pickup and return dates, then click “Book now”. You will be guided to complete the booking details and securely pay the deposit through our approved payment gateways.",
    faqCategorySecurity: "Safety & guarantees",
    faqQuestion2: "Are the money transactions and booking deposit safe?",
    faqAnswer2: "Yes, absolutely. ALTUSplace relies on a financial guarantee (escrow) system: the deposit funds remain on the certified intermediary's account until the partner confirms that the car or property was received in excellent condition.",
    faqCategoryPartners: "Partners & agencies",
    faqQuestion3: "How can I register my company or property as a partner?",
    faqAnswer3: "Go to the “Agency dashboard” page and choose to register as a car rental company or real estate developer, upload your verification documents (commercial register or national ID), and after the administration review your account will be activated right away.",
    faqCategoryCancellation: "Cancellation policy",
    faqQuestion4: "What is the cancellation and deposit refund policy?",
    faqAnswer4: "You can cancel free of charge up to 48 hours before pickup and receive a full refund of your deposit. For late cancellations, the contracted agency's terms apply as detailed in the digital contract.",

    // ─── Smart recommendations ───
    smartBadge: "Personalized suggestions",
    smartTitle: "Listed offers you might like",
    smartSourceBadge: "Based on your local browsing history",
    smartReasonFavorite: "Similar to your favorites",
    smartReasonCity: "In the city you browsed: {{city}}",
    smartReasonNewListing: "From available published listings",
    noImage: "No image",
    noVerifiedReviews: "No verified reviews",
    publishedPrice: "Published price",
    madPerDay: "MAD / day",
    madPerNight: "MAD / night",
    madPerMonth: "MAD / month",
    madPerYear: "MAD / year",

    // ─── Footer ───
    footerAddress: "Morocco — Casablanca, Marrakech, Agadir, Tangier, Rabat",
    footerNoticeLabel: "Platform protection terms",
    footerNoticeText: "The platform is only a technical and advertising intermediary and does not own or operate the cars or properties. The partner is responsible for mechanical condition, safety, cleanliness, and conformity with the description; the final relationship is governed by the written contract at handover. Fees and cancellation terms are shown before payment, and partner breaches are reviewed through the dispute resolution center in accordance with Moroccan law.",
    footerTagline: "Morocco's #1 car and property rental platform.",

    // ─── Navbar / Global UI ───
    mainNavLabel: "Main navigation",
    mobileNavLabel: "Mobile navigation",
    chooseCurrency: "Choose currency",
    currencySwitched: "Currency switched to {{currency}}",
    switchedToArabic: "تم التبديل إلى اللغة العربية",
    switchedToFrench: "Passé au français avec succès",
    switchedToEnglish: "Switched to English successfully",
    securityTwoFactor: "Manage security and two-factor authentication",
    cmiPortal: "Open CMI payment gateway",
    whatsappNotify: "Open WhatsApp notification",
    notificationsWithUnread: "Notifications, {{count}} unread",
    notificationsTitle: "Notifications & updates",
    notificationsPanelLabel: "Notifications list",
    soundOffLabel: "Turn off notification sound",
    soundOnLabel: "Turn on notification sound",
    soundEnabledLabel: "Sound on",
    soundDisabledLabel: "Sound off",
    markAllRead: "Mark all as read",
    markingAllRead: "Updating…",
    markAllReadSuccess: "All notifications marked as read",
    loginToFollowNotifications: "Log in to follow your booking notifications.",
    noNotifications: "No new notifications.",
    viewAllNotifications: "View all notifications",
    themeToLightToast: "Light mode enabled",
    themeToDarkToast: "Dark mode enabled",
    toggleThemeLabel: "Toggle dark mode",
    openSearchLabel: "Open search",
    searchTitleLabel: "Search",
    openMenuLabel: "Open menu",
    closeMenuLabel: "Close menu",
    accountSecurity: "Account security",
    cmiPaymentMobile: "CMI payment",

    // ─── App / routing ───
    loadingPage: "Loading page...",
    accessChecking: "Checking access rights...",
    loginRequired: "Login required",
    loginRequiredDesc: "Log in to access this dashboard.",
    loginAction: "Log in",
    accountInactive: "Account inactive",
    accountInactiveDesc: "This account has been suspended or blocked. Contact support for a review.",
    forbiddenTitle: "403 — Access denied",
    forbiddenDesc: "You are not authorized to open this dashboard.",
  },
};

export const SUPPORTED_LANGUAGES = ["ar", "fr", "en"] as const;

export function getDirectionForLanguage(language: Language): "rtl" | "ltr" {
  return language === "ar" ? "rtl" : "ltr";
}

export function getLocaleForLanguage(language: Language) {
  return language === "ar" ? "ar-MA" : language === "fr" ? "fr-MA" : "en-GB";
}

export function getTranslation(language: Language, key: string) {
  return translations[language][key] ?? translations.en[key] ?? translations.ar[key] ?? key;
}

/** Localized lookup with optional `{{param}}` interpolation. */
export function translate(language: Language, key: string, params?: Record<string, string | number>) {
  let text = getTranslation(language, key);
  if (params) {
    for (const [name, value] of Object.entries(params)) {
      text = text.replaceAll(`{{${name}}}`, String(value));
    }
  }
  return text;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window === "undefined") return "ar";
    const saved = readBrandPreference("language");
    return saved === "fr" || saved === "en" ? saved : "ar";
  });

  const setLanguage = (nextLanguage: Language) => {
    setLanguageState(nextLanguage);
    writeBrandPreference("language", nextLanguage);
  };

  const direction = getDirectionForLanguage(language);

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = direction;
    document.body.dir = direction;
  }, [direction, language]);

  const value = useMemo(() => ({
    language,
    direction,
    setLanguage,
    t: (key: string, params?: Record<string, string | number>) => translate(language, key, params),
  }), [direction, language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within a LanguageProvider");
  return context;
}
