import { createContext, ReactNode, useContext, useEffect, useMemo, useState } from "react";
import { readBrandPreference, writeBrandPreference } from "@/config/brand";

export type Language = "ar" | "fr" | "en";

interface LanguageContextType {
  language: Language;
  direction: "rtl" | "ltr";
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  ar: {
    home: "الرئيسية",
    cars: "تأجير السيارات",
    properties: "العقارات",
    search: "البحث والعروض",
    admin: "لوحة الإدارة",
    dashboard: "لوحة الوكالة",
    addCar: "إضافة إعلان",
    myBookings: "حجوزاتي",
    favorites: "المفضلة",
    profile: "الملف الشخصي",
    help: "الدعم والمساعدة",
    about: "عن المنصة",
    blog: "المدونة",
    notifications: "الإشعارات",
    kyc: "التحقق من الهوية",
    heroTitlePrefix: "ابحث عن",
    heroTitleCars: "أفضل السيارات",
    heroTitleAnd: "و",
    heroTitleProperties: "العقارات",
    heroTitleSuffix: "بكل سهولة",
    heroSubtitle: "منصة موثوقة لحجز السيارات والعقارات في المغرب",
    heroDescription: "منصة موثوقة لحجز السيارات والعقارات في المغرب",
    heroReviewButton: "تقييمات العملاء",
    searchTabProperties: "العقارات",
    searchTabCars: "السيارات",
    searchDropoffDate: "تاريخ الرجوع",
    searchPickupDate: "تاريخ الانطلاق",
    cityCasablanca: "الدار البيضاء",
    searchSubmitAdvanced: "بحث متقدم",
    heroBadge: "منصة معتمدة",
    searchCityOdgency: "المدينة أو الوكالة",
    popularCarBrandsTitle: "ماركات السيارات الأكثر طلباً",
    propertyTypesTitle: "أنواع العقارات المتاحة",
    bentoBadge: "مميزات المنصة",
    bentoTitle: "اكتشف تجربة حجز متكاملة",
    bentoSubtitle: "نحن نقدم لك أفضل الحلول الرقمية لتسهيل تنقلاتك وإقامتك",
    bentoRealEstateTitle: "عقارات راقية وفاخرة",
    bentoRealEstateDescription: "استكشف مجموعة مختارة من الشقق والفيلات المصممة خصيصاً لراحتك",
    bentoFleetTitle: "أسطول سيارات متنوع وعصري",
    bentoFleetDescription: "اختر من بين أحدث الموديلات السيارات الاقتصادية والرياضية لتناسب كل رحلاتك",
    browseCarsAvailable: "تصفح السيارات المتاحة",
    browsePropertiesAvailable: "تصفح العقارات المتاحة",
    viewAllListings: "عرض جميع الإعلانات",
    browseAllArticles: "تصفح جميع المقالات",
    featuredListingsBadge: "عروض مميزة",
    featuredListingsTitle: "السيارات والعقارات الأكثر طلباً هذا الأسبوع",
    blogBadge: "المدونة ونصائح السفر",
    blogTitle: "أحدث المقالات والنصائح السياحية",
    blogTravelGuideTag: "دليل السفر",
    blogCard1Title: "أفضل الوجهات السياحية للزيارة في المغرب هذه السنة",
    blogCard1Description: "اكتشف أجمل المدن والمناظر الطبيعية التي تستحق الاستكشاف في رحلتك القادمة.",
    faqBadge: "الأسئلة الشائعة",
    faqTitle: "كل ما تحتاج معرفته حول الخدمة",
    faqSubtitle: "إليك أجوبة عن أكثر الأسئلة شيوعاً لتسهيل تجربتك معنا",
    faqCategoryBooking: "شروط الحجز",
    faqQuestion1: "كيف يمكنني حجز سيارة أو عقار عبر المنصة؟",
    faqAnswer1: "يمكنك البحث عن الخدمة المطلوبة، اختيار التواريخ المناسبة، ثم الضغط على احجز الآن وإتمام الخطوات بكل سهولة.",
    faqCategorySecurity: "الأمان والدفع",
    faqQuestion2: "هل المعاملات المالية والدفع آمن؟",
    faqAnswer2: "نعم، نعتمد أحدث تقنيات التشفير لضمان حماية بياناتك الشخصية والمالية طوال عملية الحجز.",
    faqCategoryPartners: "الوكلاء والشركاء",
    faqQuestion3: "كيف يمكنني تسجيل وكالتي أو عرض عقاري؟",
    faqAnswer3: "يمكنك النقر على زر 'إضافة إعلان' أو 'لوحة الوكالة' لإنشاء حساب وكيل وإضافة عروضك مباشرة.",
    faqCategoryCancellation: "سياسة الإلغاء",
    faqQuestion4: "ما هي سياسة إلغاء الحجز والاسترداد؟",
    faqAnswer4: "يمكنك إلغاء الحجز مجاناً قبل موعد الانطلاق بـ 48 ساعة عبر صفحة حجوزاتي.",
    bookNow: "احجز الآن",
    madUnit: "درهم",
    propBusinessStudios: "ستوديو أعمال",
    propCornichePenthouses: "بنتهاوس الكورنيش",
    propModernApartments: "شقق عصرية",
    propLuxuryVillas: "فيلات فاخرة",
    propSecureResidences: "إقامات محروسة",
    blogDrivingTipsTag: "نصائح القيادة",
    blogCard3Title: "دليلك الشامل لاستئجار السيارات بأمان في المغرب",
    blogCard3Description: "تعرف على أهم الشروط والنصائح لتجنب أي رسوم خفية أثناء استئجار سيارتك.",
    blogPropInvestmentTag: "استثمار عقاري",
    blogCard2Title: "أفضل الأماكن للاستثمار العقاري والسياحي في الدار البيضاء ومراكش",
    blogCard2Description: "قراءة تحليلية لأبرز الفرص الواعدة في السوق العقاري المغربي لهذا الموسم.",
    readMore: "اقرأ المزيد",
    trustTitle1: "موثوقية عالية",
    trustDesc1: "نتعاون مع أفضل الوكلاء المعتمدين في جميع أنحاء المغرب لضمان جودة الخدمة.",
    trustTitle2: "دعم على مدار الساعة",
    trustDesc2: "فريق خدمة العملاء جاهز لمساعدتك والإجابة عن استفساراتك طوال أيام الأسبوع.",
    trustTitle3: "أفضل الأسعار المنافسة",
    trustDesc3: "نضمن لك شفافية كاملة في الأسعار بدون أي رسوم مخفية أو مفاجئة.",
    footerAddress: "الدروة، تجزئة النجمة البيضاء، الدار البيضاء، المغرب",
    footerNoticeText: "جميع الحقوق محفوظة لمنصة ألتوس بليس للحجوزات",
    readTermsAndAgree: "بالاستمرار، فإنك توافق على شروط الاستخدام وسياسة الخصوصية",
    cityAgadir: "تأجير في أكادير",
    cityMarrakech: "تأجير في مراكش",
    cityCasablancaFooter: "تأجير في الدار البيضاء",
    cityTangier: "تأجير في طنجة",
    cityRabat: "تأجير في الرباط",
  },
  fr: {
    home: "Accueil",
    cars: "Location de voitures",
    properties: "Immobilier",
    search: "Recherche et offres",
    admin: "Administration",
    dashboard: "Tableau de bord",
    addCar: "Ajouter une annonce",
    myBookings: "Mes réservations",
    favorites: "Favoris",
    profile: "Profil",
    help: "Aide et support",
    about: "À propos",
    blog: "Blog",
    notifications: "Notifications",
    kyc: "Vérification d'identité",
    heroTitlePrefix: "Trouvez les",
    heroTitleCars: "meilleures voitures",
    heroTitleAnd: "et",
    heroTitleProperties: "propriétés",
    heroTitleSuffix: "en toute simplicité",
    heroSubtitle: "Plateforme de confiance pour la location de voitures et d'immobilier au Maroc",
    heroDescription: "Plateforme de confiance pour la location de voitures et d'immobilier au Maroc",
    heroReviewButton: "Avis clients",
    searchTabProperties: "Propriétés",
    searchTabCars: "Voitures",
    searchDropoffDate: "Date de retour",
    searchPickupDate: "Date de départ",
    cityCasablanca: "Casablanca",
    searchSubmitAdvanced: "Recherche avancée",
    heroBadge: "Plateforme certifiée",
    searchCityOdgency: "Ville ou agence",
    popularCarBrandsTitle: "Marques de voitures populaires",
    propertyTypesTitle: "Types de propriétés",
    bentoBadge: "Fonctionnalités",
    bentoTitle: "Découvrez une expérience de réservation complète",
    bentoSubtitle: "Nous vous offrons les meilleures solutions numériques pour vos déplacements et séjours",
    bentoRealEstateTitle: "Immobilier haut de gamme",
    bentoRealEstateDescription: "Explorez une sélection d'appartements et de villas conçus pour votre confort",
    bentoFleetTitle: "Flotte de véhicules moderne et variée",
    bentoFleetDescription: "Choisissez parmi les derniers modèles de voitures économiques et sportives",
    browseCarsAvailable: "Parcourir les voitures",
    browsePropertiesAvailable: "Parcourir les propriétés",
    viewAllListings: "Voir toutes les annonces",
    browseAllArticles: "Parcourir tous les articles",
    featuredListingsBadge: "Offres en vedette",
    featuredListingsTitle: "Les véhicules et propriétés les plus demandés cette semaine",
    blogBadge: "Blog et guides",
    blogTitle: "Derniers articles et conseils de voyage",
    blogTravelGuideTag: "Guide de voyage",
    blogCard1Title: "Les meilleures destinations touristiques à visiter au Maroc cette année",
    blogCard1Description: "Découvrez les plus belles villes et paysages à explorer lors de votre prochain voyage.",
    faqBadge: "FAQ",
    faqTitle: "Tout ce que vous devez savoir",
    faqSubtitle: "Retrouvez les réponses aux questions les plus fréquentes",
    faqCategoryBooking: "Réservation",
    faqQuestion1: "Comment réserver une voiture ou un bien immobilier ?",
    faqAnswer1: "Recherchez, choisissez vos dates et cliquez sur Réserver pour finaliser facilement.",
    faqCategorySecurity: "Sécurité",
    faqQuestion2: "Les paiements en ligne sont-ils sécurisés ?",
    faqAnswer2: "Oui, nous utilisons des protocoles de cryptage avancés pour protéger vos données.",
    faqCategoryPartners: "Partenaires",
    faqQuestion3: "Comment enregistrer mon agence ou mon bien ?",
    faqAnswer3: "Cliquez sur Ajouter une annonce pour créer votre compte partenaire.",
    faqCategoryCancellation: "Annulation",
    faqQuestion4: "Quelle est la politique d'annulation ?",
    faqAnswer4: "Annulation gratuite jusqu'à 48 heures avant la prise en charge.",
    bookNow: "Réserver",
    madUnit: "MAD",
    propBusinessStudios: "Studios d'affaires",
    propCornichePenthouses: "Penthouses Corniche",
    propModernApartments: "Appartements modernes",
    propLuxuryVillas: "Villas de luxe",
    propSecureResidences: "Résidences sécurisées",
    blogDrivingTipsTag: "Conseils de conduite",
    blogCard3Title: "Votre guide complet pour louer une voiture en toute sécurité au Maroc",
    blogCard3Description: "Découvrez les conditions et conseils clés pour éviter les frais cachés.",
    blogPropInvestmentTag: "Investissement",
    blogCard2Title: "Les meilleurs endroits pour investir dans l'immobilier à Casablanca et Marrakech",
    blogCard2Description: "Analyse des opportunités prometteuses sur le marché immobilier marocain.",
    readMore: "Lire la suite",
    trustTitle1: "Haute Fiabilité",
    trustDesc1: "Partenariat avec les meilleures agences certifiées à travers le Maroc.",
    trustTitle2: "Support 24/7",
    trustDesc2: "Notre équipe est à votre disposition pour répondre à toutes vos questions.",
    trustTitle3: "Meilleurs Prix",
    trustDesc3: "Transparence totale des tarifs sans aucun frais caché.",
    footerAddress: "Deroua, Lotissement Etoile Blanche, Casablanca, Maroc",
    footerNoticeText: "Tous droits réservés pour Altus Place",
    readTermsAndAgree: "En continuant, vous acceptez les conditions d'utilisation",
    cityAgadir: "Louer à Agadir",
    cityMarrakech: "Louer à Marrakech",
    cityCasablancaFooter: "Louer à Casablanca",
    cityTangier: "Louer à Tanger",
    cityRabat: "Louer à Rabat",
  },
  en: {
    home: "Home",
    cars: "Car Rental",
    properties: "Properties",
    search: "Search & Offers",
    admin: "Admin Dashboard",
    dashboard: "Agency Dashboard",
    addCar: "Add Listing",
    myBookings: "My Bookings",
    favorites: "Favorites",
    profile: "Profile",
    help: "Help & Support",
    about: "About Us",
    blog: "Blog",
    notifications: "Notifications",
    kyc: "Identity Verification",
    heroTitlePrefix: "Find the best",
    heroTitleCars: "cars",
    heroTitleAnd: "and",
    heroTitleProperties: "properties",
    heroTitleSuffix: "with ease",
    heroSubtitle: "Trusted platform for car rental and real estate in Morocco",
    heroDescription: "Trusted platform for car rental and real estate in Morocco",
    heroReviewButton: "Customer Reviews",
    searchTabProperties: "Properties",
    searchTabCars: "Cars",
    searchDropoffDate: "Drop-off Date",
    searchPickupDate: "Pickup Date",
    cityCasablanca: "Casablanca",
    searchSubmitAdvanced: "Advanced Search",
    heroBadge: "Verified Platform",
    searchCityOdgency: "City or Agency",
    popularCarBrandsTitle: "Popular Car Brands",
    propertyTypesTitle: "Property Types",
    bentoBadge: "Platform Features",
    bentoTitle: "Discover a seamless booking experience",
    bentoSubtitle: "We provide the best digital solutions to ease your travel and stay",
    bentoRealEstateTitle: "Luxury Real Estate",
    bentoRealEstateDescription: "Explore a curated selection of apartments and villas designed for your comfort",
    bentoFleetTitle: "Modern & Diverse Car Fleet",
    bentoFleetDescription: "Choose from the latest economic and sports car models for your trips",
    browseCarsAvailable: "Browse Available Cars",
    browsePropertiesAvailable: "Browse Available Properties",
    viewAllListings: "View All Listings",
    browseAllArticles: "Browse All Articles",
    featuredListingsBadge: "Featured Offers",
    featuredListingsTitle: "Most Popular Cars and Properties This Week",
    blogBadge: "Blog & Travel Tips",
    blogTitle: "Latest Articles and Tourism Tips",
    blogTravelGuideTag: "Travel Guide",
    blogCard1Title: "Top Tourist Destinations to Visit in Morocco This Year",
    blogCard1Description: "Discover the most beautiful cities and landscapes worth exploring on your next trip.",
    faqBadge: "FAQ",
    faqTitle: "Everything you need to know about our service",
    faqSubtitle: "Find answers to the most common questions to smooth your experience",
    faqCategoryBooking: "Booking",
    faqQuestion1: "How can I book a car or a property?",
    faqAnswer1: "Search for your choice, select dates, and click Book Now to easily complete.",
    faqCategorySecurity: "Security",
    faqQuestion2: "Are online payments secure?",
    faqAnswer2: "Yes, we use advanced encryption to protect your personal and financial data.",
    faqCategoryPartners: "Partners",
    faqQuestion3: "How can I register my agency or property?",
    faqAnswer3: "Click Add Listing to create an agent account and list your offers.",
    faqCategoryCancellation: "Cancellation",
    faqQuestion4: "What is the cancellation and refund policy?",
    faqAnswer4: "You can cancel for free up to 48 hours before pickup.",
    bookNow: "Book Now",
    madUnit: "MAD",
    propBusinessStudios: "Business Studios",
    propCornichePenthouses: "Corniche Penthouses",
    propModernApartments: "Modern Apartments",
    propLuxuryVillas: "Luxury Villas",
    propSecureResidences: "Secure Residences",
    blogDrivingTipsTag: "Driving Tips",
    blogCard3Title: "Your comprehensive guide to safe car rental in Morocco",
    blogCard3Description: "Learn about key terms and tips to avoid hidden fees during your rental.",
    blogPropInvestmentTag: "Real Estate",
    blogCard2Title: "Best places for real estate and tourism investment in Casablanca and Marrakech",
    blogCard2Description: "An analytical review of promising opportunities in the Moroccan real estate market.",
    readMore: "Read More",
    trustTitle1: "High Reliability",
    trustDesc1: "Collaborating with top certified agencies across Morocco.",
    trustTitle2: "24/7 Support",
    trustDesc2: "Our customer service team is ready to assist you every day.",
    trustTitle3: "Best Competitive Prices",
    trustDesc3: "We guarantee complete transparency with no hidden fees.",
    footerAddress: "Deroua, Lotissement Etoile Blanche, Casablanca, Morocco",
    footerNoticeText: "All rights reserved for Altus Place",
    readTermsAndAgree: "By continuing, you agree to the Terms of Service and Privacy Policy",
    cityAgadir: "Rent in Agadir",
    cityMarrakech: "Rent in Marrakech",
    cityCasablancaFooter: "Rent in Casablanca",
    cityTangier: "Rent in Tanger",
    cityRabat: "Rent in Rabat",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("ar");

  useEffect(() => {
    const brand = readBrandPreference();
    if (brand && ["ar", "fr", "en"].includes(brand.defaultLanguage)) {
      setLanguageState(brand.defaultLanguage as Language);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    const brand = readBrandPreference();
    writeBrandPreference({ ...brand, defaultLanguage: lang });
  };

  const direction = language === "ar" ? "rtl" : "ltr";

  useEffect(() => {
    document.documentElement.dir = direction;
    document.documentElement.lang = language;
  }, [direction, language]);

  const t = (key: string): string => {
    return translations[language]?.[key] || translations["en"]?.[key] || key;
  };

  const value = useMemo(() => ({ language, direction, setLanguage, t }), [language, direction]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}